# Numpy for 1D array

In [1]:
import numpy as np

In [2]:
#Craete a numpy array
array_ = np.array([1,2,3,4,5,6,7,8,9,10])
#print the array
print(array_)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#print the dimention, shape, data type

print("the dimnetion of this array is = ",array_.ndim)
print("the shape of this array is     =",array_.shape)
print("the data type of this array is =",array_.dtype)

the dimnetion of this array is =  1
the shape of this array is     = (10,)
the data type of this array is = int32


In [4]:
#Create zeros

#In np.zeros((row, colum))
zeros_ = np.zeros((10,))
print("the zeros_ :\n", zeros_,'\n')

print('the dimention of this array is = ', zeros_.ndim)
print('the shape of this array is     =', zeros_.shape)
print('the data type of this array is =', zeros_.dtype)

the zeros_ :
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

the dimention of this array is =  1
the shape of this array is     = (10,)
the data type of this array is = float64


In [5]:
#In np.zeros, default the data type is "float", so we can change it using "astype"

zeros_ = zeros_.astype('int64')
print("the array after changing the data type:\n", zeros_,'\n')

#Is it the only option to do. Answer is no. when we build np.zeros() there we have a option dtype. there we can change.

store_ = np.zeros((10,), dtype = 'int64')

print("the array which i created with int64 data type:\n", store_,'\n')

the array after changing the data type:
 [0 0 0 0 0 0 0 0 0 0] 

the array which i created with int64 data type:
 [0 0 0 0 0 0 0 0 0 0] 



In [6]:
#print the array_
print("the array is: \n", array_,'\n')
print("the array of zeros:\n",store_,'\n')

the array is: 
 [ 1  2  3  4  5  6  7  8  9 10] 

the array of zeros:
 [0 0 0 0 0 0 0 0 0 0] 



In [7]:
#print the length 
print('the size of array is       = ', array_.size)
print('the size of store array is = ',store_.size)

the size of array is       =  10
the size of store array is =  10


In [8]:
#copy the array data into store array using list and dictonary

list_ = []
dict_ = {}
keys_ = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
# for value_ in np.nditer(array_):
#     print("value = ", value_)
    
# output:
    
# value =  1
# value =  2
# value =  3
# value =  4
# value =  5
# value =  6
# value =  7
# value =  8
# value =  9
# value =  10

row_ = array_.shape[0]
print("the number of rows is = ", row_)

for value_ in range(row_):
    list_.append(array_[value_])
    dict_[keys_[value_]] = array_[value_]

print("the list is = ", list_)
print("the dict is = ", dict_)

#just store the data into store 

store_ = list_

print("the store array contains: ", store_)

#store data using loop

for index_, value_ in enumerate(list_):
    zeros_[index_] = value_
print("the zeros contains : ", zeros_)

#print the dictonary and store the value
list1_ = []

for value_ in dict_.values():
    list1_.append(value_)

print('the list1 contains: ', list1_)

array1_ = np.random.rand(10)
print('the array1 contains: ', array1_)

#now store the list1_ data to array1_

array1_ = list1_

print("the array1 contains now: ", array1_)

the number of rows is =  10
the list is =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
the dict is =  {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'I': 9, 'J': 10}
the store array contains:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
the zeros contains :  [ 1  2  3  4  5  6  7  8  9 10]
the list1 contains:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
the array1 contains:  [0.0108663  0.85124037 0.88555569 0.71304089 0.33615815 0.79679003
 0.99198802 0.04175259 0.02223271 0.02446167]
the array1 contains now:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
print("the array is = ", array_)

the array is =  [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
#Check 5 is presence or not

if 5 in array_:
    print("Yes, its presence")
else:
    print("No, its not presence")

Yes, its presence


In [11]:
#if we need to index of 5 value then use 'argmax'
index_ = np.where(array_ == 5)
print("The index is = ", index_[0])

#Check that in that index the value is presence or not

print("the value is = ", array_[index_])

The index is =  [4]
the value is =  [5]


In [12]:
#If i want to check 3,4,5 value is presence or not then use "np.in1d"

np.in1d(array_, [3,4,10])
#it gives the 1d array with boolean
#output:
# array([False,  True,  True, False,  True, False, False, False, False,
#        False])

print("Index are = ",array_[np.in1d(array_, [3,4,10])])

# index_ = array_[np.in1d(array_, [3,4,10])]

# print("the index are = ", index_)

#now find the value of those index

index_ = np.where(np.in1d(array_, [3,4,10]))
print("the index are = ", index_[0])

#Check the value is really presence or not

print("the value is = ",array_[index_])

Index are =  [ 3  4 10]
the index are =  [2 3 9]
the value is =  [ 3  4 10]


In [13]:
#Slicing

print(array_)

#print the last 5 data
print("the last five data is = ", array_[-5:])
#print the first 3 data
print('the first three data is = ', array_[:3])
#print the 4,5th index value
print("the 4th and 5th index's data is = ", array_[[3,4]])

[ 1  2  3  4  5  6  7  8  9 10]
the last five data is =  [ 6  7  8  9 10]
the first three data is =  [1 2 3]
the 4th and 5th index's data is =  [4 5]


In [14]:
#array_split

print(array_)
split_ = np.array_split(array_, 3)

print("the split array is = ", split_)

#using loop we need to print

list_ = []
for value_ in split_:
    print("the split values: ", value_,'\n')
    list_.append(value_)

print("the list is : ", list_)

[ 1  2  3  4  5  6  7  8  9 10]
the split array is =  [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
the split values:  [1 2 3 4] 

the split values:  [5 6 7] 

the split values:  [ 8  9 10] 

the list is :  [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [15]:
#Now, we want to add those the same way as it was

print("after using hstack the array looks like = ",np.hstack(split_))

after using hstack the array looks like =  [ 1  2  3  4  5  6  7  8  9 10]


In [16]:
#some arithmatic operation 

print("the sum of this array is = ", np.sum(array_))
print("the mean of this array is = ", np.mean(array_))
print("the std of this array is = ", np.std(array_))
print("the max value of this array is = ", np.max(array_))
print("the min value of this array is = ", np.min(array_))

the sum of this array is =  55
the mean of this array is =  5.5
the std of this array is =  2.8722813232690143
the max value of this array is =  10
the min value of this array is =  1


In [17]:
#Find the unique value 

print("the unique value of this array is = ",np.unique(array_))

#How many times the unique value occurs

unique_, counts_ = np.unique(array_, return_counts = True)

print("Unique = ", unique_, "value_counts_ = ", counts_)

the unique value of this array is =  [ 1  2  3  4  5  6  7  8  9 10]
Unique =  [ 1  2  3  4  5  6  7  8  9 10] value_counts_ =  [1 1 1 1 1 1 1 1 1 1]


In [18]:
#Sort the value
array_.sort()
print("the sort value is = ",array_)

the sort value is =  [ 1  2  3  4  5  6  7  8  9 10]


In [19]:
#Linspace
print("the linspace value is = ",np.linspace(start = 1, stop = 30, num = 30))
#Reshape
array_ = array_.reshape(2,5)
print('after reshaping the value is = ', array_)

the linspace value is =  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
after reshaping the value is =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 2D NUMPY

In [20]:
array_ = np.arange(start = 20.1, stop = 40.1, dtype = 'float64')
print(array_)

[20.1 21.1 22.1 23.1 24.1 25.1 26.1 27.1 28.1 29.1 30.1 31.1 32.1 33.1
 34.1 35.1 36.1 37.1 38.1 39.1]


In [21]:
#now reshape it 10*8
array_ = array_.reshape(5,4)
print(array_)
print(array_.ndim)

[[20.1 21.1 22.1 23.1]
 [24.1 25.1 26.1 27.1]
 [28.1 29.1 30.1 31.1]
 [32.1 33.1 34.1 35.1]
 [36.1 37.1 38.1 39.1]]
2


In [22]:
array1_ = np.random.rand(20)
array1_ = array1_.reshape(5,4)
print(array1_)
print(array1_.ndim)

[[0.23026491 0.60504874 0.38357941 0.58706932]
 [0.40397886 0.62630971 0.13260374 0.99772995]
 [0.81459207 0.97344876 0.73835401 0.99565992]
 [0.24924398 0.60806533 0.06958223 0.44155837]
 [0.16911349 0.42385377 0.54829295 0.37918782]]
2


In [23]:
#now add this in a numpy using concatenate
concatenate_ = np.concatenate((array_, array1_), axis = 0)
concatenate_

array([[20.1       , 21.1       , 22.1       , 23.1       ],
       [24.1       , 25.1       , 26.1       , 27.1       ],
       [28.1       , 29.1       , 30.1       , 31.1       ],
       [32.1       , 33.1       , 34.1       , 35.1       ],
       [36.1       , 37.1       , 38.1       , 39.1       ],
       [ 0.23026491,  0.60504874,  0.38357941,  0.58706932],
       [ 0.40397886,  0.62630971,  0.13260374,  0.99772995],
       [ 0.81459207,  0.97344876,  0.73835401,  0.99565992],
       [ 0.24924398,  0.60806533,  0.06958223,  0.44155837],
       [ 0.16911349,  0.42385377,  0.54829295,  0.37918782]])

In [24]:
#now add this in a numpy using vstack
vstack_ = np.vstack((array_,array1_))
vstack_

array([[20.1       , 21.1       , 22.1       , 23.1       ],
       [24.1       , 25.1       , 26.1       , 27.1       ],
       [28.1       , 29.1       , 30.1       , 31.1       ],
       [32.1       , 33.1       , 34.1       , 35.1       ],
       [36.1       , 37.1       , 38.1       , 39.1       ],
       [ 0.23026491,  0.60504874,  0.38357941,  0.58706932],
       [ 0.40397886,  0.62630971,  0.13260374,  0.99772995],
       [ 0.81459207,  0.97344876,  0.73835401,  0.99565992],
       [ 0.24924398,  0.60806533,  0.06958223,  0.44155837],
       [ 0.16911349,  0.42385377,  0.54829295,  0.37918782]])

In [25]:
#check whether two are same or not
vstack_ == concatenate_

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
array_ = vstack_

In [27]:
#now change the data type

array_ = array_.astype('int64')
array_

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]], dtype=int64)

In [28]:
#after changing the data type the value of a couple of rows and columns turns zero; now fill the value with random number

array_ == 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
#now find the index
index_ = np.where(np.in1d(array_, array_ == 0))
print(index_)

index_ = list(index_[0])

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39], dtype=int64),)


In [30]:
#now find the 2D index


def retrive(index_):
    row_ = array_.shape[0]
    col_ = array_.shape[1]

    dict_  = {}
    count_ = 0 
    
    for row in range(row_):
        for col in range(col_):
            dict_[count_] = [row, col]
            count_ = count_ + 1
            
    return dict_[index_]

list_  = []
for data_ in index_:
    print(retrive(data_))
    random_ = np.random.randint(10,50)
    print(random_)
    array_[retrive(data_)[0], retrive(data_)[1]] = random_

array_
    

[5, 0]
15
[5, 1]
31
[5, 2]
33
[5, 3]
34
[6, 0]
29
[6, 1]
26
[6, 2]
24
[6, 3]
39
[7, 0]
17
[7, 1]
48
[7, 2]
13
[7, 3]
21
[8, 0]
21
[8, 1]
22
[8, 2]
41
[8, 3]
29
[9, 0]
30
[9, 1]
44
[9, 2]
22
[9, 3]
41


array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [15, 31, 33, 34],
       [29, 26, 24, 39],
       [17, 48, 13, 21],
       [21, 22, 41, 29],
       [30, 44, 22, 41]], dtype=int64)

In [31]:
#print the array_
array_

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [15, 31, 33, 34],
       [29, 26, 24, 39],
       [17, 48, 13, 21],
       [21, 22, 41, 29],
       [30, 44, 22, 41]], dtype=int64)

In [32]:
#split the dataset

np.array_split(array_, 3)

# output:
# [array([[20, 21, 22, 23],
#         [24, 25, 26, 27],
#         [28, 29, 30, 31],
#         [32, 33, 34, 35]], dtype=int64),
#  array([[36, 37, 38, 39],
#         [20, 26, 17, 39],
#         [38, 17, 33, 16]], dtype=int64),
#  array([[25, 29, 16, 32],
#         [38, 39, 31, 16],
#         [32, 31, 42, 34]], dtype=int64)]

[array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]], dtype=int64),
 array([[36, 37, 38, 39],
        [15, 31, 33, 34],
        [29, 26, 24, 39]], dtype=int64),
 array([[17, 48, 13, 21],
        [21, 22, 41, 29],
        [30, 44, 22, 41]], dtype=int64)]

In [33]:
#split the datset:
split_ = np.array_split(array_, 3)
split_

[array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]], dtype=int64),
 array([[36, 37, 38, 39],
        [15, 31, 33, 34],
        [29, 26, 24, 39]], dtype=int64),
 array([[17, 48, 13, 21],
        [21, 22, 41, 29],
        [30, 44, 22, 41]], dtype=int64)]

In [34]:
#store this split dataset in a new array_

zeros_ = np.zeros((array_.shape[0],array_.shape[1]), dtype = 'int64')
zeros_

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [35]:
split_[0].shape

(4, 4)

In [36]:
previous_ = 0

count = 0

for values_ in split_:

    if count == 0:
        zeros_[0:values_.shape[0],:] = values_
        count = count + 1
        previous_ = previous_ + values_.shape[0]
    else:
        zeros_[previous_:previous_+values_.shape[0],:] = values_
        previous_ = previous_ + values_.shape[0]

zeros_

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [15, 31, 33, 34],
       [29, 26, 24, 39],
       [17, 48, 13, 21],
       [21, 22, 41, 29],
       [30, 44, 22, 41]], dtype=int64)

In [37]:
#now we will merge the sub array using vstack

merge_ = np.vstack(split_)
merge_

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [15, 31, 33, 34],
       [29, 26, 24, 39],
       [17, 48, 13, 21],
       [21, 22, 41, 29],
       [30, 44, 22, 41]], dtype=int64)

In [38]:
print("zeros_ array has dimention = ", zeros_.ndim)
print("merge_ array has dimention = ", merge_.ndim)
print("zeros_ array has shape = ", zeros_.shape)
print("merge_ array has shape = ", merge_.shape)
print("sum of zeros_ = ", sum(sum(zeros_)))
print("sum of zeros_ = ", sum(sum(merge_)))

zeros_ array has dimention =  2
merge_ array has dimention =  2
zeros_ array has shape =  (10, 4)
merge_ array has shape =  (10, 4)
sum of zeros_ =  1170
sum of zeros_ =  1170


In [39]:
#Check two array has same element or not using iterative

for data1_, data2_ in zip(merge_, zeros_):
    print(data1_, data2_)

[20 21 22 23] [20 21 22 23]
[24 25 26 27] [24 25 26 27]
[28 29 30 31] [28 29 30 31]
[32 33 34 35] [32 33 34 35]
[36 37 38 39] [36 37 38 39]
[15 31 33 34] [15 31 33 34]
[29 26 24 39] [29 26 24 39]
[17 48 13 21] [17 48 13 21]
[21 22 41 29] [21 22 41 29]
[30 44 22 41] [30 44 22 41]


In [40]:
check_ = merge_ == zeros_
print(check_.all(),": - means two numpy array has same data:")

True : - means two numpy array has same data:


In [41]:
merge1_ = merge_.copy()
merge1_

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [15, 31, 33, 34],
       [29, 26, 24, 39],
       [17, 48, 13, 21],
       [21, 22, 41, 29],
       [30, 44, 22, 41]], dtype=int64)

In [42]:
#change just one element
merge1_[0,0] = -20

merge1_

array([[-20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 15,  31,  33,  34],
       [ 29,  26,  24,  39],
       [ 17,  48,  13,  21],
       [ 21,  22,  41,  29],
       [ 30,  44,  22,  41]], dtype=int64)

In [43]:
#Now check two numpy array has same element or not

check_= merge1_ == zeros_
print(check_.all(),": - means two numpy array has no same value")

False : - means two numpy array has no same value


In [44]:
#Seed Function used_

array_ = np.random.rand(20)
array_

# output:
# array([0.64177338, 0.77661364, 0.16394576, 0.90402666, 0.82011204,
#        0.19806071, 0.15275763, 0.6079709 , 0.0253648 , 0.85090399,
#        0.98351251, 0.23394804, 0.66714399, 0.74475932, 0.18348242,
#        0.86544879, 0.05239989, 0.9917028 , 0.41768067, 0.19039941])

array([0.45761448, 0.64447512, 0.71960169, 0.28564097, 0.39614611,
       0.09201408, 0.78814089, 0.91553958, 0.31112772, 0.01864181,
       0.34150165, 0.75535128, 0.13209754, 0.7016078 , 0.18255957,
       0.34091797, 0.79679315, 0.90929582, 0.84964834, 0.09914434])

In [45]:
#If i want to take 2D array using random.rand(row,column)
array_ = np.random.rand(4,5)
array_

# output:
# array([[0.78211176, 0.78570192, 0.53245874, 0.31182262, 0.04744965],
#        [0.47884196, 0.7740885 , 0.78306403, 0.99123627, 0.97703521],
#        [0.29556605, 0.19747933, 0.39715195, 0.46657199, 0.33410868],
#        [0.91613972, 0.0710225 , 0.7938765 , 0.03837921, 0.90423262]])

array([[0.43163648, 0.72329754, 0.3265922 , 0.75853443, 0.10563137],
       [0.32194446, 0.40122287, 0.55052481, 0.93653691, 0.10940103],
       [0.45660179, 0.24405065, 0.26609997, 0.68608539, 0.96215856],
       [0.03817626, 0.55072534, 0.0927245 , 0.70099548, 0.244669  ]])

In [46]:
array1_ = array_.copy()
array1_

array([[0.43163648, 0.72329754, 0.3265922 , 0.75853443, 0.10563137],
       [0.32194446, 0.40122287, 0.55052481, 0.93653691, 0.10940103],
       [0.45660179, 0.24405065, 0.26609997, 0.68608539, 0.96215856],
       [0.03817626, 0.55072534, 0.0927245 , 0.70099548, 0.244669  ]])

In [47]:
#check two array is same or not

check_ = array1_ == array_

if check_.all() == True:
    print('same')
else:
    print('not same')
    
#How to oercome from this problem. Solution is using 'random.seed(12)' before calling the random.rand or some other function

np.random.seed(12)

newArray_ = np.random.rand(4,4)
print("the array is: \n",newArray_,'\n')
copy_array_ = newArray_.copy()

print("the copy array is: \n", copy_array_)

check_ = newArray_ == copy_array_

if check_.all() == True:
    print("\n two aray is same: ")
else:
    print('\n two array is not same:')

same
the array is: 
 [[0.15416284 0.7400497  0.26331502 0.53373939]
 [0.01457496 0.91874701 0.90071485 0.03342143]
 [0.95694934 0.13720932 0.28382835 0.60608318]
 [0.94422514 0.85273554 0.00225923 0.52122603]] 

the copy array is: 
 [[0.15416284 0.7400497  0.26331502 0.53373939]
 [0.01457496 0.91874701 0.90071485 0.03342143]
 [0.95694934 0.13720932 0.28382835 0.60608318]
 [0.94422514 0.85273554 0.00225923 0.52122603]]

 two aray is same: 


In [48]:
#Using random.randint(start, stop, (row, column))

array_ = np.random.randint(1, 12, (3,4))
print("the array is: \n", array_,'\n')
print("the dimnetion is = ", array_.ndim)
print("the shape is = ", array_.shape,'\n')


#If i want to print 3D array then random.randint(start, stop, (2- means 3D, row, column))

array1_ = np.random.randint(1, 12, (2,3,2))
print("the array is : \n",array1_,'\n')
print("the dimnetion is = ", array1_.ndim)
print("the shape is = ", array1_.shape,'\n')

the array is: 
 [[ 8  1  3  7]
 [ 3  1  5  7]
 [10  1  1 10]] 

the dimnetion is =  2
the shape is =  (3, 4) 

the array is : 
 [[[ 9 10]
  [ 7  2]
  [ 9  5]]

 [[ 1  5]
  [ 2  6]
  [ 6  4]]] 

the dimnetion is =  3
the shape is =  (2, 3, 2) 



In [49]:
#Using random.random ((row, column))

array_ = np.random.random(10)
print("the array is = \n",array_,'\n')
print("the dimnetion is = ", array_.ndim)
print("the shape is = ", array_.shape,'\n')

#Create 2D

array_ = np.random.random((4,3))
print("the array is = \n",array_,'\n')
print("the dimnetion is = ", array_.ndim)
print("the shape is = ", array_.shape,'\n')


the array is = 
 [0.95031352 0.76747565 0.82500925 0.4066403  0.45130841 0.40063163
 0.99513816 0.17756418 0.9625969  0.41925027] 

the dimnetion is =  1
the shape is =  (10,) 

the array is = 
 [[0.42405245 0.46314887 0.37372315]
 [0.4655081  0.03516826 0.08427267]
 [0.7325207  0.63619999 0.02790779]
 [0.30017006 0.22085252 0.05501999]] 

the dimnetion is =  2
the shape is =  (4, 3) 



In [50]:
#Using ravel and permutation

array_ = np.arange(10).reshape(5,2)
print("the array is = \n",array_, "\n")
print("the dimention of this array is = ", array_.ndim,"\n")
print("the shape of this array is = ", array_.shape,"\n")

#If i want to take just 1D then use ravel

ravel_ = np.ravel(array_)
print("the 1D array is = ", ravel_)

#sort the value

np.sort(ravel_)

the array is = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

the dimention of this array is =  2 

the shape of this array is =  (5, 2) 

the 1D array is =  [0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#Sorting Use

np.random.seed(12)
array_ = np.random.randint(10,100, (10,10))
print("the array is : \n", array_,'\n')

#Using sort

np.sort(array_)

the array is : 
 [[85 37 16 12 13 77 86 58 32 59]
 [62 15 23 99 44 85 84 10 86 23]
 [92 99 45 72 45 43 40 73 28 96]
 [60 90 94 16 83 55 40 42 37 69]
 [99 69 98 89 35 66 14 78 75 54]
 [47 85 78 63 85 63 57 70 52 80]
 [80 77 12 38 84 68 69 94 64 65]
 [94 30 39 79 61 53 42 53 28 80]
 [44 63 68 10 47 30 90 77 97 67]
 [64 66 78 35 54 32 79 19 69 37]] 



array([[12, 13, 16, 32, 37, 58, 59, 77, 85, 86],
       [10, 15, 23, 23, 44, 62, 84, 85, 86, 99],
       [28, 40, 43, 45, 45, 72, 73, 92, 96, 99],
       [16, 37, 40, 42, 55, 60, 69, 83, 90, 94],
       [14, 35, 54, 66, 69, 75, 78, 89, 98, 99],
       [47, 52, 57, 63, 63, 70, 78, 80, 85, 85],
       [12, 38, 64, 65, 68, 69, 77, 80, 84, 94],
       [28, 30, 39, 42, 53, 53, 61, 79, 80, 94],
       [10, 30, 44, 47, 63, 67, 68, 77, 90, 97],
       [19, 32, 35, 37, 54, 64, 66, 69, 78, 79]])

In [52]:
#User define sort

data_type = np.dtype([('name', 'string_'),('data', 'float')])

array_ = np.array([('abc', 190.56), ('bdc',100.10)],dtype = data_type)
print(array_)
print(np.sort(array_, order = 'data'))

[(b'', 190.56) (b'', 100.1 )]
[(b'', 100.1 ) (b'', 190.56)]


In [53]:
#Shuffle

array_ = np.arange(100).reshape(10,10)
print(array_)

#now do the shuffle

np.random.shuffle(array_)
array_

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [54]:
#How to use random.choice
np.random.choice(np.ravel(array_))

59

# Practise Session

In [55]:
#first create 2*5 matrix with "integer value"

array1_ = np.arange(0,10, dtype = 'int64').reshape(2,5)

print("the first array is: \n", array1_)

the first array is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
#Create another array with 2*5 with "integer"

array2_ = np.random.randint(11,21, (2,5))
print("the second array looks like: \n", array2_)

the second array looks like: 
 [[15 14 19 19 17]
 [20 19 15 20 15]]


In [57]:
#Create an another array with 2*5 matrix with "float"

np.random.seed(12)
array3_ = np.random.rand(2,5)
print("the third array looks like: \n", array3_)

the third array looks like: 
 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]]


In [58]:
#now modify the third array, which value .5222 it will be represent 52, 0.74 will be represent as 74

array3_ = array3_*100
array3_ = np.floor(array3_)
array3_ = array3_.astype(int)

print("after ceiling the third array looks like: \n",array3_)

after ceiling the third array looks like: 
 [[15 74 26 53  1]
 [91 90  3 95 13]]


In [59]:
#Create a list where random number will be presence and create foutrh array with 2*5 matrix

list_ = []

np.random.seed(12)
random_ = np.random.random((2,5))
random_ = np.ravel(random_)
print("the random value is: \n",random_,'\n')
print("the type of this random value is: ", type(random_),'\n')
print("the data type of this random value is: ", random_.dtype,'\n')

#now convert the float64 to int

random_ = random_*100
random_ = np.ceil(random_)
random_ = random_.astype(int)
print("after ceiling the array looks like: ", random_)

the random value is: 
 [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496 0.91874701
 0.90071485 0.03342143 0.95694934 0.13720932] 

the type of this random value is:  <class 'numpy.ndarray'> 

the data type of this random value is:  float64 

after ceiling the array looks like:  [16 75 27 54  2 92 91  4 96 14]


In [60]:
random_ = list(random_)
print("after converting the numpy array into list, the array looks like: ", random_,'\n')
print("the type of this is: ", type(random_))

after converting the numpy array into list, the array looks like:  [16, 75, 27, 54, 2, 92, 91, 4, 96, 14] 

the type of this is:  <class 'list'>


In [61]:
#Now create the fourth matrix

dummy_ = np.zeros((2,5), dtype = 'int64')
print("the dummy shape looks like: \n", dummy_,'\n')
print("the dimention of this dummy is: ",dummy_.ndim,'\n')
print("the shape of this dummy is: ", dummy_.shape,'\n')

row_ = np.arange(0, dummy_.shape[0])
print("the row is:", row_,'\n')
col_ = np.arange(0, dummy_.shape[1])
print("the col_ is:", col_)



the dummy shape looks like: 
 [[0 0 0 0 0]
 [0 0 0 0 0]] 

the dimention of this dummy is:  2 

the shape of this dummy is:  (2, 5) 

the row is: [0 1] 

the col_ is: [0 1 2 3 4]


In [62]:
import itertools

for combination_ in list(itertools.product(row_,col_)):
    print(combination_)
#here in itertools.product(there is no need pass the [], ok ?)  

# output:
# (0, 0)
# (0, 1)
# (0, 2)
# (0, 3)
# (0, 4)
# (1, 0)
# (1, 1)
# (1, 2)
# (1, 3)
# (1, 4)

for index_, combination_ in enumerate(list(itertools.product(row_,col_))):
    print(index_, combination_)
    
# output:
# 0 (0, 0)
# 1 (0, 1)
# 2 (0, 2)
# 3 (0, 3)
# 4 (0, 4)
# 5 (1, 0)
# 6 (1, 1)
# 7 (1, 2)
# 8 (1, 3)
# 9 (1, 4)


(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(1, 4)
0 (0, 0)
1 (0, 1)
2 (0, 2)
3 (0, 3)
4 (0, 4)
5 (1, 0)
6 (1, 1)
7 (1, 2)
8 (1, 3)
9 (1, 4)


In [63]:
#now create a combination of rows and columns
import itertools

for index_, combination_ in enumerate(list(itertools.product(row_, col_))):
    dummy_[combination_] = random_[index_]

In [64]:
print("the dummy_ array looks like: \n",dummy_,'\n')
print('the shape of this dummy_ is: ', dummy_.shape,'\n')
print("the dimention of this dummy is:", dummy_.ndim,'\n')
print("the type of this dummy is: ", dummy_.dtype)

the dummy_ array looks like: 
 [[16 75 27 54  2]
 [92 91  4 96 14]] 

the shape of this dummy_ is:  (2, 5) 

the dimention of this dummy is: 2 

the type of this dummy is:  int64


In [65]:
#Now print the all the array which we created so far

print("the first array is: \n", array1_,'\n')
print("the second array is: \n", array2_,'\n')
print("the third array is: \n", array3_,'\n')
print("the fourth array is: \n", dummy_,'\n')

the first array is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

the second array is: 
 [[15 14 19 19 17]
 [20 19 15 20 15]] 

the third array is: 
 [[15 74 26 53  1]
 [91 90  3 95 13]] 

the fourth array is: 
 [[16 75 27 54  2]
 [92 91  4 96 14]] 



In [66]:
#Now merge all the sub array 

array_ = np.vstack((array1_, array2_, array3_, dummy_))

print("the merge_ array looks like: \n", array_,'\n')
print("the dimention of this array is:", array_.ndim,'\n')
print("the shape of this array is:", array_.shape,'\n')
print("the type of this array is:", type(array_),'\n')
print("the data data type of this array is:", array_.dtype,'\n')

the merge_ array looks like: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 14 19 19 17]
 [20 19 15 20 15]
 [15 74 26 53  1]
 [91 90  3 95 13]
 [16 75 27 54  2]
 [92 91  4 96 14]] 

the dimention of this array is: 2 

the shape of this array is: (8, 5) 

the type of this array is: <class 'numpy.ndarray'> 

the data data type of this array is: int64 



In [67]:
array = array_.copy()

In [68]:
#Now in that certain array, find the even number and put there odd numbers randomly: using iteratively and print it

#Check
array_%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False,  True, False, False, False],
       [ True, False, False,  True, False],
       [False,  True,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False,  True,  True,  True]])

In [69]:
#Now find the index_

index_ = np.where(array_%2==0)
print("the index is = ", index_)

the index is =  (array([0, 0, 0, 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 6, 7, 7, 7, 7], dtype=int64), array([0, 2, 4, 1, 3, 1, 0, 3, 1, 2, 1, 0, 3, 4, 0, 2, 3, 4], dtype=int64))


In [70]:
#Print the combination of index_
for row_, col_ in zip(index_[0], index_[1]):
    print(row_, col_)

0 0
0 2
0 4
1 1
1 3
2 1
3 0
3 3
4 1
4 2
5 1
6 0
6 3
6 4
7 0
7 2
7 3
7 4


In [71]:
#now create some odd numbers randomly

def random_generate():
    random_odd_ = -1
    while True:
        odd_ = np.random.randint(1,18)
        if odd_%2 == 0:
            continue
        else:
            random_odd_ = odd_
            break
    return random_odd_

In [72]:
#Now, store the odd value in the even number 

for row_, col_ in zip(index_[0], index_[1]):
    odd_ = random_generate()
    array_[row_, col_] = odd_

array_

array([[ 1,  1,  9,  3, 13],
       [ 5,  5,  7,  1,  9],
       [15, 17, 19, 19, 17],
       [ 7, 19, 15, 17, 15],
       [15,  1, 15, 53,  1],
       [91,  5,  3, 95, 13],
       [ 1, 75, 27,  5, 13],
       [ 5, 91,  1, 11,  7]], dtype=int64)

In [73]:
#Now Check whether that certain array really contains all odd items or not

check_ = array_%2!=0

if check_.all() == True:
    print('All are even:')
else:
    print("there might be having odd")

All are even:


In [74]:
#Check that code really works or not
dummy = array_.copy()
dummy[0,0] = 26

check_ = dummy%2!=0

if check_.all() == True:
    print('All are even:')
else:
    print("there might be having odd")

there might be having odd


In [75]:
#Do the same things using np.where(condition, action postive, action negative)

print("the array looks like: \n", array,'\n')

odd_ = np.where(array%2 == 0, random_generate(), array)

print("the odd looks like: \n", odd_,'\n')

check_ = odd_%2 == 0

if check_.all() == True:
    print('there might be having odd numbers')
else:
    print('All are odd_')

the array looks like: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 14 19 19 17]
 [20 19 15 20 15]
 [15 74 26 53  1]
 [91 90  3 95 13]
 [16 75 27 54  2]
 [92 91  4 96 14]] 

the odd looks like: 
 [[ 7  1  7  3  7]
 [ 5  7  7  7  9]
 [15  7 19 19 17]
 [ 7 19 15  7 15]
 [15  7  7 53  1]
 [91  7  3 95 13]
 [ 7 75 27  7  7]
 [ 7 91  7  7  7]] 

All are odd_


In [76]:
#How to Use Lambda

# list_ = [1,2,3,4,5,6,7,8,9,10]

# fuc_ = lambda lis_: lis_ if (lis_!=5) else 'false'
# add_ = fuc_(list_)
# print(add_)

function_ = lambda number1_, number2_: 'True' if (number1_>number2_) else 'False'

print(function_(10,5))

True


In [77]:
list_ = [1,2,3,4,5,266, 6,7,8,9,10]
func_ = lambda list_: True if (len(list_) == 10) else False
print(func_(list_))
max(list_)

False


266

In [78]:
list_ = [1,2,3,4,5,6,7,8,9,10]

func_ = list(filter(lambda list_: list_>5, list_))
print(func_)

[6, 7, 8, 9, 10]


In [79]:
list_ = [11, 12, 13, 14, 15, 16, 17, 18, 19]
print(list_)

func_ = list(map(lambda value_: np.sqrt(value_), list_))
print(func_)

[11, 12, 13, 14, 15, 16, 17, 18, 19]
[3.3166247903554, 3.4641016151377544, 3.605551275463989, 3.7416573867739413, 3.872983346207417, 4.0, 4.123105625617661, 4.242640687119285, 4.358898943540674]


In [80]:
list_ = [[3,1,2],[4,6,5],[8,10,9,6]]
list1_ = [[3,1,2],[4,6,5],[8,10,9,6]]
list2_ = [1,2,3,4,5,6]
print(list_,'\n')

list_.sort(reverse = False)
print("after sorting: ", list_,'\n')
#it doesn't sort due to it contains 2D. what we will have to do is write a loop and in loop we will sort

for index_, value_ in enumerate(list_):
    print("index", index_, "contains: ",value_)
    value_.sort(reverse = False)
    
print(' ')

print("after sorting the value of that list_ looks like: \n", list_,'\n')


#Here, we were using loop just to do a sort, we can use it in different ways

sort_ = [sorted(value_, reverse = False) for value_ in list_]
print("after sorting the list_ looks like: \n", sort_)

[[3, 1, 2], [4, 6, 5], [8, 10, 9, 6]] 

after sorting:  [[3, 1, 2], [4, 6, 5], [8, 10, 9, 6]] 

index 0 contains:  [3, 1, 2]
index 1 contains:  [4, 6, 5]
index 2 contains:  [8, 10, 9, 6]
 
after sorting the value of that list_ looks like: 
 [[1, 2, 3], [4, 5, 6], [6, 8, 9, 10]] 

after sorting the list_ looks like: 
 [[1, 2, 3], [4, 5, 6], [6, 8, 9, 10]]


In [81]:
#Some opration in a list

np.random.seed(12)
array_ = np.random.random((4,5))
print("the random array looks like: \n", array_,'\n')
print("the dimnention of this array is: ", array_.ndim,'\n0')
print("the shape of this array is: ", array_.shape,'\n')
print("the data type of this array is:", array_.dtype,'\n')
print("the type of this array is: ", type(array),'\n')

#Now convert this array into 1D

# array_ = np.ravel(array_)
# print("after converting the array looks like: \n",array_,'\n')
# print("the dimnention of this array is: ", array_.ndim,'\n')
# print("the shape of this array is: ", array_.shape,'\n')
# print("the data type of this array is:", array_.dtype,'\n')
# print("the type of this array is: ", type(array),'\n')

#Conert numpy to list; it will convert the same way as it was there in numpy, if numpy was 2D then the same way(2D) it will be..
list_ = array_.tolist()

# output:

# [[0.15416284237967237,
#   0.7400496965154048,
#   0.26331501518513467,
#   0.5337393933802977,
#   0.014574962485419674],
#  [0.918747008099885,
#   0.9007148541170122,
#   0.03342142762634459,
#   0.9569493362751168,
#   0.13720932135607644],
#  [0.28382835295794584,
#   0.6060831843588289,
#   0.9442251360530421,
#   0.852735541109285,
#   0.002259233518513537],
#  [0.5212260272202929,
#   0.5520376332645666,
#   0.4853774136627097,
#   0.7681341540644223,
#   0.1607167531255701]]

#Now sort the list_ as Descending order

sorted_ = [sorted(value_, reverse = True) for value_ in list_]
print("the sort list looks like: \n", sorted_)

#Now i want to take those value who is grater then >0.50

found_ = [[(value > .50)for value in value_] for value_ in sorted_]
found_

the random array looks like: 
 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]] 

the dimnention of this array is:  2 
0
the shape of this array is:  (4, 5) 

the data type of this array is: float64 

the type of this array is:  <class 'numpy.ndarray'> 

the sort list looks like: 
 [[0.7400496965154048, 0.5337393933802977, 0.26331501518513467, 0.15416284237967237, 0.014574962485419674], [0.9569493362751168, 0.918747008099885, 0.9007148541170122, 0.13720932135607644, 0.03342142762634459], [0.9442251360530421, 0.852735541109285, 0.6060831843588289, 0.28382835295794584, 0.002259233518513537], [0.7681341540644223, 0.5520376332645666, 0.5212260272202929, 0.4853774136627097, 0.1607167531255701]]


[[True, True, False, False, False],
 [True, True, True, False, False],
 [True, True, True, False, False],
 [True, True, True, False, False]]

In [82]:
found_

[[True, True, False, False, False],
 [True, True, True, False, False],
 [True, True, True, False, False],
 [True, True, True, False, False]]

In [83]:
index_ = [[(index, each_index_) for each_index_, value_ in enumerate(check_) if value_ == True] for index, check_ in enumerate(found_)]

In [84]:
index_

[[(0, 0), (0, 1)],
 [(1, 0), (1, 1), (1, 2)],
 [(2, 0), (2, 1), (2, 2)],
 [(3, 0), (3, 1), (3, 2)]]

In [85]:
list_ = []
dummy_ = np.zeros(10000, dtype = 'float')
for index in index_:
    count = 0
    for each in index:
#         print(each[0], each[1])
        dummy_[count] = sorted_[each[0]][each[1]]
#         print(sorted_[each[0]][each[1]])
        count = count + 1
#     print("dummy = ",dummy_[:count])
    list_.append(dummy_[0:count].tolist())
    print("list_ ",list_)
#     dummy_[0:count] = 0
    print(' ')
list_

list_  [[0.7400496965154048, 0.5337393933802977]]
 
list_  [[0.7400496965154048, 0.5337393933802977], [0.9569493362751168, 0.918747008099885, 0.9007148541170122]]
 
list_  [[0.7400496965154048, 0.5337393933802977], [0.9569493362751168, 0.918747008099885, 0.9007148541170122], [0.9442251360530421, 0.852735541109285, 0.6060831843588289]]
 
list_  [[0.7400496965154048, 0.5337393933802977], [0.9569493362751168, 0.918747008099885, 0.9007148541170122], [0.9442251360530421, 0.852735541109285, 0.6060831843588289], [0.7681341540644223, 0.5520376332645666, 0.5212260272202929]]
 


[[0.7400496965154048, 0.5337393933802977],
 [0.9569493362751168, 0.918747008099885, 0.9007148541170122],
 [0.9442251360530421, 0.852735541109285, 0.6060831843588289],
 [0.7681341540644223, 0.5520376332645666, 0.5212260272202929]]

In [86]:
list_

[[0.7400496965154048, 0.5337393933802977],
 [0.9569493362751168, 0.918747008099885, 0.9007148541170122],
 [0.9442251360530421, 0.852735541109285, 0.6060831843588289],
 [0.7681341540644223, 0.5520376332645666, 0.5212260272202929]]

In [87]:
[[(Index) for Index in index] for index in index_]

[[(0, 0), (0, 1)],
 [(1, 0), (1, 1), (1, 2)],
 [(2, 0), (2, 1), (2, 2)],
 [(3, 0), (3, 1), (3, 2)]]

In [88]:
[(0, 0), (0, 1)]
[(1, 0), (1, 1), (1, 2)]

(0, 0)
(0, 1)

(0, 1)

In [89]:
# index       check_
# 0     [True, True, False, False, False]
# 1     [True, True, True, False, False]

 
# True- 0, True- 1, False - 2, False-3, False - 4

In [90]:
for value_ in list_:
    for value in value_:
        print(value)
    print(' ')

# output:
# 0.7400496965154048
# 0.5337393933802977
 
# 0.9569493362751168
# 0.918747008099885
# 0.9007148541170122
 
# 0.9442251360530421
# 0.852735541109285
# 0.6060831843588289
 
# 0.7681341540644223
# 0.5520376332645666
# 0.5212260272202929

for value_ in list_:
    list1_ = []
    for value in value_:
        list1_.append(value+100)
    print(list1_)
    
# output:
# [[100.7400496965154, 100.5337393933803],
#  [100.95694933627512, 100.91874700809988, 100.90071485411701],
#  [100.94422513605305, 100.85273554110928, 100.60608318435882],
#  [100.76813415406443, 100.55203763326456, 100.5212260272203]]


#We do this in a single line

[[(value+100) for value in value_] for value_ in list_]

# output:
# [[100.7400496965154, 100.5337393933803],
#  [100.95694933627512, 100.91874700809988, 100.90071485411701],
#  [100.94422513605305, 100.85273554110928, 100.60608318435882],
#  [100.76813415406443, 100.55203763326456, 100.5212260272203]]

0.7400496965154048
0.5337393933802977
 
0.9569493362751168
0.918747008099885
0.9007148541170122
 
0.9442251360530421
0.852735541109285
0.6060831843588289
 
0.7681341540644223
0.5520376332645666
0.5212260272202929
 
[100.7400496965154, 100.5337393933803]
[100.95694933627512, 100.91874700809988, 100.90071485411701]
[100.94422513605305, 100.85273554110928, 100.60608318435882]
[100.76813415406443, 100.55203763326456, 100.5212260272203]


[[100.7400496965154, 100.5337393933803],
 [100.95694933627512, 100.91874700809988, 100.90071485411701],
 [100.94422513605305, 100.85273554110928, 100.60608318435882],
 [100.76813415406443, 100.55203763326456, 100.5212260272203]]

# Lambda 


In [91]:
##For 1D array

list_ = [1,2,3,4,5,6,7,8,9,10]

func_ = lambda take_: take_

print(func_(list_))

#if i want to take two list then

list1_ = [1,2,3,4,5,6,7,8,9,10]
list2_ = [10,9,8,7,6,5,4,3,2,1]

func_ = lambda take1_, take2_ : take1_== take2_

if func_(list1_, list2_) == False:
    print('False means- the two lists are not same')
else:
    print('True maens- two lists are same')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
False means- the two lists are not same


In [92]:
list_ = [10,77,88,10,72,93,73]

print("the list is = ", list_)

the list is =  [10, 77, 88, 10, 72, 93, 73]


In [93]:
#If i want to add by 2 to all list items then

def add(data_):
    
    return data_ + 2

# list1_ = []

# for value_ in list_:
    
#     list1_.append(value_ + 2)
    
# print('after adding, the list is = ', list1_)

# output:
# after adding, the list is =  [12, 79, 90, 12, 74, 95, 75]

#We can do it by using "MAP"

# func_ = list(map(add, list_))

# print("after adding, the list_ looks like: ", func_)

# output:
# after adding, the list_ looks like:  [12, 79, 90, 12, 74, 95, 75]

#We can change the function -(add) by using lambda

func_ = list(map(lambda data_: data_ + 2, list_))
print("after adding the data is = ", func_)

# output:
# after adding the data is =  [12, 79, 90, 12, 74, 95, 75]

after adding the data is =  [12, 79, 90, 12, 74, 95, 75]


# Map and Lambda

In [94]:
#If it possible to add two list

list1_ = [1,2,3]
list2_ = [4,5,6]


def add_(data1_, data2_):
    
    return data1_ + data2_

list3_ = []

# for list1_, list2_ in zip(list1_, list2_):
    
#     print(list1_, list2_)
    
# output:
# 1 4
# 2 5
# 3 6

#Now i will add two list


# for list1_, list2_ in zip(list1_, list2_):
#     print(add_(list1_, list2_))
#     list3_.append(add_(list1_, list2_))

# print("after adding the list looks like: ",list3_)

# output:
# after adding the list looks like:  [5, 7, 9]

#i will do using map

# func_ = list(map(add_, list1_, list2_))
# print("after adding, the list looks like: ", func_)

# output:
# after adding, the list looks like:  [5, 7, 9]

#We can do it using lambda and map

# func_ = tuple(map(lambda x,y: x + y, list1_, list2_))
# print("after adding, the list looks like: ", func_)

# output:
# after adding, the list looks like:  (5, 7, 9)

# def mul_(data1_, data2_):
    
#     return data1_*3, data2_*4

# func_ = list(map(mul_, list1_, list2_))

# print("after multiplying, the list looks like: ", func_)

# output:
# after multiplying, the list looks like:  [(3, 16), (6, 20), (9, 24)]

#NOW, i want [3,6,9]*3 = [3,6,9], then add with list_ and the result will be like:[7,11,15]

func1_ = list(map(lambda x: x*3, list1_))
func_  = list(map(lambda x, y: x + y, func1_, list2_))

print("after operation, the list_ looks like: ",func_)

after operation, the list_ looks like:  [7, 11, 15]


# Filter Method with Lambda

In [95]:
#create a list_

list_ = [10, 13, 16, 20, 21, 17]

print("the list_ looks like:", list_,'\n')

#i want to get even number from the list 

list1_ = []

for value_ in list_:
    if value_ %2 == 0:
        list1_.append(value_)
    else:
        continue

print("the Even number list looks like: ", list1_,'\n')


#We can do the same thing using filter method, what filter method does is return the value on the basis of "True"

# def even_(data_):
    
#     if data_ %2 == 0:
#         return True
#     else:
#         return False
    
# func_ = list(filter(even_, list_))

# print("the Even number list looks like: ", func_)

# output:
# the Even number list looks like:  [10, 16, 20]

#We can do this process using lambda

# func_ = list(filter(lambda x: (x%2==0), list_))

# print("the Even number list looks like: ", func_)

# output:
# the Even number list looks like:  [10, 16, 20]


#now i want to print: which value > 15 and print the list; then, print the odd and even and add two list_ and print the sum

func1_ = list(filter(lambda x: (x>15), list_))

print("The list, which contains value greater than 15, is : ", func1_,'\n')

#output:
#The list, which contains value greater than 15, is:  [16, 20, 21, 17]
#Now print the even number from that func1_

even_ = list(filter(lambda y: (y%2==0), func1_))

print("the Even number of this list is, after being sliced: ", even_,'\n')

# output:
# the Even number of this list is, after being sliced:  [10, 16, 20]

odd_ = list(filter(lambda z: (z%2!=0), func1_))

print("the Odd number of this list is, after being sliced : ", odd_,'\n')

# output:
# the Odd number of this list is, after being sliced :  [21, 17] 
#Now add two list:

add_ = list(map(lambda x, y: (x + y), even_, odd_))

print("after adding the list looks like: ", add_,'\n')

# output:
# after adding the list looks like:  [37, 37]

#Get the total sum:

sum_ = list(map(lambda x: x+x , add_ ))

print("after adding the total sum is = ", sum_[0])

the list_ looks like: [10, 13, 16, 20, 21, 17] 

the Even number list looks like:  [10, 16, 20] 

The list, which contains value greater than 15, is :  [16, 20, 21, 17] 

the Even number of this list is, after being sliced:  [16, 20] 

the Odd number of this list is, after being sliced :  [21, 17] 

after adding the list looks like:  [37, 37] 

after adding the total sum is =  74


In [96]:
#Collection Use

list_ = [1,2,1,2,3,4,1,3,4,5,6,1,6,3,10,3,5,1,4,2,45,1,3,1,4,1,34]

print("the list is = ", list_,'\n')

#find how many times the data occurs using iterative

dict_ = {}

count = 0
for value_ in list_:
    count = 0
    for data_ in list_:
        if value_ == data_:
            count = count + 1
    dict_[value_] = count
    
print("the dictonary is = ", dict_,'\n')
print("the sum of value is = ", sum(dict_.values()),'\n')
print("the length of list_ was = ", len(list_),'\n')


#Now we will do the same things using building function

from collections import Counter

list_ = Counter(list_)
print("the list_ looks like: ", list_,'\n')
print("the keys of this counter is: ", list_.keys(),'\n')
print("the values of this counter is: ", list_.values(),'\n')
print("the most frequent value is: ", list_.most_common(1),'\n')
print("the top 3 most common is: ", list_.most_common(3),'\n')
print("the unique value is = ", list_.keys())


the list is =  [1, 2, 1, 2, 3, 4, 1, 3, 4, 5, 6, 1, 6, 3, 10, 3, 5, 1, 4, 2, 45, 1, 3, 1, 4, 1, 34] 

the dictonary is =  {1: 8, 2: 3, 3: 5, 4: 4, 5: 2, 6: 2, 10: 1, 45: 1, 34: 1} 

the sum of value is =  27 

the length of list_ was =  27 

the list_ looks like:  Counter({1: 8, 3: 5, 4: 4, 2: 3, 5: 2, 6: 2, 10: 1, 45: 1, 34: 1}) 

the keys of this counter is:  dict_keys([1, 2, 3, 4, 5, 6, 10, 45, 34]) 

the values of this counter is:  dict_values([8, 3, 5, 4, 2, 2, 1, 1, 1]) 

the most frequent value is:  [(1, 8)] 

the top 3 most common is:  [(1, 8), (3, 5), (4, 4)] 

the unique value is =  dict_keys([1, 2, 3, 4, 5, 6, 10, 45, 34])


In [97]:
#Add element in a list

list_ = [1,2,3,4,5,6]

#i want to add 10

list_.append(10)
print("after adding 10, the list looks like = ", list_)

#but i want to add 10 in first index !, then use collections

from collections import deque

deque_ = deque(list_)
print("the deque is = ", deque_)
#now add 10 in the first

deque_.appendleft(10)
deque_

after adding 10, the list looks like =  [1, 2, 3, 4, 5, 6, 10]
the deque is =  deque([1, 2, 3, 4, 5, 6, 10])


deque([10, 1, 2, 3, 4, 5, 6, 10])

In [98]:
#Delete Duplicate Values

list_ = [[1,2,1,3,4,2], [3,5,3,2,1,4,5,1]]

print("the 2D list is = ", list_,'\n')

# dict_.fromkeys(list_[0])
#output
#{1: None, 2: None, 3: None, 4: None} - it gives the dictonary but we need a list; so convert into a list
# list(dict_.fromkeys(list_[0]))
#output:
#[1, 2, 3, 4] = after using list it gives the list

delete_ = []
for values_ in list_:
    delete_.append(list(dict.fromkeys(values_)))

print("after deleting the duplicate value, the list looks like = ",delete_,'\n')

#sort as a asceding order
new_list_ = [sorted(values_, reverse = False) for values_ in delete_]

print("the new list_ = ", new_list_)

the 2D list is =  [[1, 2, 1, 3, 4, 2], [3, 5, 3, 2, 1, 4, 5, 1]] 

after deleting the duplicate value, the list looks like =  [[1, 2, 3, 4], [3, 5, 2, 1, 4]] 

the new list_ =  [[1, 2, 3, 4], [1, 2, 3, 4, 5]]


In [99]:
# dict_.fromkeys(list_[0])
#{1: None, 2: None, 3: None, 4: None} - it gives the dictonary but we need a list; so convert into a list
# list(dict_.fromkeys(list_[0]))
#[1, 2, 3, 4] = after using list it gives the list

# Practise Session

In [100]:
#Create a list which contains 10 elements

np.random.seed(12)
random_ = np.random.randint(1, 10, (2,5))
print("type of this random is         = ", type(random_),'\n')
print("the dimention of this array is = ", random_.ndim,'\n')
print("the shape of this array is     = ", random_.shape,'\n')
print("the data type of this array is = ", random_.dtype,'\n')

print('--------------------------------------------------------')

#first, we will have to create 1D array, where 10 data will be presence

random_ = np.ravel(random_)

print("the 1D numpy array is          = ", random_,'\n')
print("the dimention of this array is = ", random_.ndim,'\n')
print("the shape of this array is     = ", random_.shape,'\n')
print("the data type of this array is = ", random_.dtype,'\n')
print("the length of this array is    = ", len(random_),'\n')

print('--------------------------------------------------------')
#Now just convert this " <class 'numpy.ndarray'> " to list

list1_ = random_.tolist()

print("After converting, the list looks like: ", list1_)

type of this random is         =  <class 'numpy.ndarray'> 

the dimention of this array is =  2 

the shape of this array is     =  (2, 5) 

the data type of this array is =  int32 

--------------------------------------------------------
the 1D numpy array is          =  [7 2 3 4 4 1 7 2 5 6] 

the dimention of this array is =  1 

the shape of this array is     =  (10,) 

the data type of this array is =  int32 

the length of this array is    =  10 

--------------------------------------------------------
After converting, the list looks like:  [7, 2, 3, 4, 4, 1, 7, 2, 5, 6]


In [101]:
list1_

[7, 2, 3, 4, 4, 1, 7, 2, 5, 6]

In [102]:
#Now, check the list1 contains dupdlicate value or not; if so then delete those, and put random number

from collections import Counter

def check_duplicate(list_):
    
    counter_ = Counter(list_)
    
    return len(counter_.keys())

def fill_duplicate_(list_):
    
    unique_        = list(dict.fromkeys(list_))
    unique_length_ = len(unique_)
    list_length_   = len(list_)
    count_         = 0
    data_          = np.random.randint(200)
    
    while(unique_length_ != list_length_):
        if data_ in unique_:
            while True:
                data_ = np.random.randint(20)
                if data_ in unique_:
                    continue
                else:
                    unique_.append(data_)
                    unique_length_ = unique_length_ + 1
                    break
        else:
            unique_.append(data_)
            unique_length_ = unique_length_ + 1
        
    return unique_


length_     = check_duplicate(list1_)
real_length = len(list1_)

print("the length after finding duplicate is = ", length_, '\n')
print("the length of real list1_ is          = ", len(list1_),'\n')

#Now, check the length is equal or not, if equal then it means - no duplicate and vice versa

list_ = fill_duplicate_(list1_)
if length_ != real_length:
    
    print('there is some duplicate values: \n')
    list_ = fill_duplicate_(list1_)
    print("the unique list is = ", list_)
else:
    print("the list1_ does not have duplicate values:")

the length after finding duplicate is =  7 

the length of real list1_ is          =  10 

there is some duplicate values: 

the unique list is =  [7, 2, 3, 4, 1, 5, 6, 128, 8, 12]


In [103]:
def odd_generator(list_):
    
    length_   = len(list_)
    odd_list_ = []
    
    while(length_ != 0):
        
        data_ = np.random.randint(201,501)
        
        if data_ %2 == 0:
            continue
        else:
            odd_list_.append(data_)
            length_ = length_ -1
    return odd_list_

In [104]:
#Now, this list will be contained only odd value

even_ = list(filter(lambda x: (x%2==0), list_))

print("the even list is = ", even_,'\n')

odd_ = list(filter(lambda x: (x%2!=0), list_))
print("the even list is = ", odd_,'\n')

odd_list_ = odd_generator(even_)
print("the new list is = ", odd_list_,'\n')

#add the old odd and new add

list_ = odd_ + odd_list_
print("the total odd list is = ", list_)

the even list is =  [2, 4, 6, 128, 8, 12] 

the even list is =  [7, 3, 1, 5] 

the new list is =  [283, 301, 359, 347, 409, 335] 

the total odd list is =  [7, 3, 1, 5, 283, 301, 359, 347, 409, 335]


In [105]:
#Now create an numpy array with that list

array_ = np.array(list_)
array_ = array_.reshape(2,5)

print("the array is: \n\n", array_,'\n')
print("the dimention of this array is = ", array_.ndim,'\n')
print("the shape of this array is     = ", array_.shape,'\n')
print("the type of this array is      = ", type(array_),'\n')
print("the data type of this array is = ", array_.dtype)

the array is: 

 [[  7   3   1   5 283]
 [301 359 347 409 335]] 

the dimention of this array is =  2 

the shape of this array is     =  (2, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32


In [106]:
#Create an another 2D array randomly with 2*5 matrix will be presence

np.random.seed(12)
array1_ = np.arange(1,11).reshape(2,5)

print("the second numpy array looks like: \n\n", array1_,'\n')
print("the dimention of this array is = ", array1_.ndim,'\n')
print("the shape of this array is     = ", array1_.shape,'\n')
print("the type of this array is      = ", type(array1_),'\n')
print("the data type of this array is = ", array1_.dtype)

the second numpy array looks like: 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

the dimention of this array is =  2 

the shape of this array is     =  (2, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32


In [107]:
#Create an another array randomly with 2*5 matrix will be presence, but in this case we will have to take float

np.random.seed(12)
array2_ = np.random.random((2,5))
print("the third numpy array looks like: \n\n", array2_,'\n')
print("the dimention of this array is = ", array2_.ndim,'\n')
print("the shape of this array is     = ", array2_.shape,'\n')
print("the type of this array is      = ", type(array2_),'\n')
print("the data type of this array is = ", array2_.dtype)

# what we will have to do is change the array. Ex: 0.15416284 and 0.91874701 this value will be 1.07290985 then print
# 1.07290985 will be 107. 290985, then it will be ceiled 108 and to be continued ! 

row_   = np.arange(0, array2_.shape[0],dtype = 'int32')
col_   = np.arange(0, array2_.shape[1],dtype = 'int32')
dummy_ = np.arange(0, array2_.shape[1],dtype = 'float')
print("the row is    = ", row_,'\n')
print("the column is =  ", col_,'\n')
print("the column is =  ", dummy_,'\n')

slice_ = []

for value_ in col_:
    dummy_[value_] = np.sum(array2_[:, value_])
print("the dummy array looks like: ", dummy_)


#We can do this things as easy way

# np.sum(array2_, axis = 0)

the third numpy array looks like: 

 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]] 

the dimention of this array is =  2 

the shape of this array is     =  (2, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  float64
the row is    =  [0 1] 

the column is =   [0 1 2 3 4] 

the column is =   [0. 1. 2. 3. 4.] 

the dummy array looks like:  [1.07290985 1.64076455 0.29673644 1.49068873 0.15178428]


In [108]:
array2_ = np.array([dummy_])
array2_ = array2_*150
array2_ = array2_.astype('int32')
print("the third numpy array looks like: \n\n", array2_,'\n')
print("the dimention of this array is = ", array2_.ndim,'\n')
print("the shape of this array is     = ", array2_.shape,'\n')
print("the type of this array is      = ", type(array2_),'\n')
print("the data type of this array is = ", array2_.dtype)

the third numpy array looks like: 

 [[160 246  44 223  22]] 

the dimention of this array is =  2 

the shape of this array is     =  (1, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32


In [109]:
print("the array is: \n\n", array_,'\n')
print("the dimention of this array is = ", array_.ndim,'\n')
print("the shape of this array is     = ", array_.shape,'\n')
print("the type of this array is      = ", type(array_),'\n')
print("the data type of this array is = ", array_.dtype)

print('--------------------------------------------------------')

print("the array is: \n\n", array1_,'\n')
print("the dimention of this array is = ", array1_.ndim,'\n')
print("the shape of this array is     = ", array1_.shape,'\n')
print("the type of this array is      = ", type(array1_),'\n')
print("the data type of this array is = ", array1_.dtype)

print('--------------------------------------------------------')

print("the array is: \n\n", array2_,'\n')
print("the dimention of this array is = ", array2_.ndim,'\n')
print("the shape of this array is     = ", array2_.shape,'\n')
print("the type of this array is      = ", type(array2_),'\n')
print("the data type of this array is = ", array2_.dtype)

the array is: 

 [[  7   3   1   5 283]
 [301 359 347 409 335]] 

the dimention of this array is =  2 

the shape of this array is     =  (2, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32
--------------------------------------------------------
the array is: 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

the dimention of this array is =  2 

the shape of this array is     =  (2, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32
--------------------------------------------------------
the array is: 

 [[160 246  44 223  22]] 

the dimention of this array is =  2 

the shape of this array is     =  (1, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32


In [110]:
#Now Merge the array 

array_ = np.vstack((array_, array1_, array2_))

print("the array is: \n\n", array_,'\n')
print("the dimention of this array is = ", array_.ndim,'\n')
print("the shape of this array is     = ", array_.shape,'\n')
print("the type of this array is      = ", type(array_),'\n')
print("the data type of this array is = ", array_.dtype)

the array is: 

 [[  7   3   1   5 283]
 [301 359 347 409 335]
 [  1   2   3   4   5]
 [  6   7   8   9  10]
 [160 246  44 223  22]] 

the dimention of this array is =  2 

the shape of this array is     =  (5, 5) 

the type of this array is      =  <class 'numpy.ndarray'> 

the data type of this array is =  int32


In [111]:
#Split the array_

split_ = np.array_split(array_, 3, axis = 0)
split_

[array([[  7,   3,   1,   5, 283],
        [301, 359, 347, 409, 335]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[160, 246,  44, 223,  22]])]

In [112]:
list(split_)[0]

array([[  7,   3,   1,   5, 283],
       [301, 359, 347, 409, 335]])

In [113]:
np.vstack((split_[0],split_[1], split_[2]))

array([[  7,   3,   1,   5, 283],
       [301, 359, 347, 409, 335],
       [  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [160, 246,  44, 223,  22]])

In [114]:
def reshape_(array_):
    
    shape_ = np.where((array_>100), np.ceil(array_/100), array_)
    shape_ = shape_.astype('int32')
    return shape_.tolist()

In [115]:
list_ = []
dummy_ = np.zeros((1,5))
for split_array_ in split_:
    print(split_array_)
    print(' ')
    print(reshape_(split_array_))
    dummy_ = np.append(dummy_,reshape_(split_array_), axis = 0 )
    print(' ')
    add_ = (np.vstack(reshape_(split_array_)))
    list_.append(add_)
    
dummy_ = dummy_[1:]
dummy_ = dummy_.astype('int')
dummy_

[[  7   3   1   5 283]
 [301 359 347 409 335]]
 
[[7, 3, 1, 5, 3], [4, 4, 4, 5, 4]]
 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
 
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
 
[[160 246  44 223  22]]
 
[[2, 3, 44, 3, 22]]
 


array([[ 7,  3,  1,  5,  3],
       [ 4,  4,  4,  5,  4],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  3, 44,  3, 22]])

In [116]:
array_ = dummy_
print("the final array is = ",array_)

the final array is =  [[ 7  3  1  5  3]
 [ 4  4  4  5  4]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2  3 44  3 22]]


In [117]:
##Numpy append

array_ = np.array([[]])

print("the dimnetion of this array is = ", array_.ndim)

array_ = np.append(array_, [[1,2,3,4]],axis = 1)
print("the array looks like: ", array_)

array_ = np.append(array_,[[5,6,7,8]], axis = 0)
print("the array looks like: \n", array_)

array_ = np.append(array_,[[15,16,17,18]], axis = 0)
print("the array looks like: \n", array_)

the dimnetion of this array is =  2
the array looks like:  [[1. 2. 3. 4.]]
the array looks like: 
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
the array looks like: 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [15. 16. 17. 18.]]


In [118]:
demo_ = np.zeros((5,5))
demo_

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [119]:
split_[0]

array([[  7,   3,   1,   5, 283],
       [301, 359, 347, 409, 335]])

In [120]:
np.append(demo_, split_[0] , axis = 0)

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  7.,   3.,   1.,   5., 283.],
       [301., 359., 347., 409., 335.]])

# Numpy append

In [121]:
#Create a 2D empty numpy

array_ = np.array([[]])

print("the empy array looks like: ", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')

the empy array looks like:  [] 

the dimention of this array is:  2 



In [122]:
#Now, we want to add 2,3,4 then 

array_ = np.append(array_, [[2,3,4]], axis = 1)
#we put axis = 1, because first we will insert the items as column wise
print("the empy array looks like: ", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')
print(' ')

#now we will put some other elements

np.random.seed(12)
random_ = np.random.random((3,3))
print("the empy array looks like: \n\n", random_,'\n')
print("the dimention of this array is: ", random_.ndim,'\n')
print(' ')

#now we will insert all of these value into array_

for values_ in random_:
    print("the array looks like: ",values_)
    print("the dimnetion of this array is: ", values_.ndim)
    print(' ')
    #here, we see that the dimention of these each array is 1d, but in array_ dimnetion was 2, so will have to add "[]"
    array_ = np.append(array_, [values_], axis = 0)
    #here, why have we used axis = 0, ans: now "[0.15416284 0.7400497  0.26331502]" will be added like row wise 


the empy array looks like:  [[2. 3. 4.]] 

the dimention of this array is:  2 

 
the empy array looks like: 

 [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] 

the dimention of this array is:  2 

 
the array looks like:  [0.15416284 0.7400497  0.26331502]
the dimnetion of this array is:  1
 
the array looks like:  [0.53373939 0.01457496 0.91874701]
the dimnetion of this array is:  1
 
the array looks like:  [0.90071485 0.03342143 0.95694934]
the dimnetion of this array is:  1
 


In [123]:
#print the array_
print("the empy array looks like: \n\n", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')
print(' ')

the empy array looks like: 

 [[2.         3.         4.        ]
 [0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] 

the dimention of this array is:  2 

 


In [124]:
#Do the same thing using np.zeros

dummy_array_ = np.zeros((1,5))

print("the dummy array looks like: \n\n", dummy_array_,'\n')
print("the dimention of this array is: ", dummy_array_.ndim,'\n')
print("the shape of this array is: ", dummy_array_.shape,'\n')
print("the type of this array is: ", type(dummy_array_),'\n')
print("the data type of this array is: ", (dummy_array_.dtype),'\n')


the dummy array looks like: 

 [[0. 0. 0. 0. 0.]] 

the dimention of this array is:  2 

the shape of this array is:  (1, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [125]:
#Create a random array with 5*5 matrix

np.random.seed(12)
random_ = np.random.random((5,5))

print("the random_ array looks like: \n\n", random_,'\n')
print("the dimention of this array is: ", random_.ndim,'\n')
print("the shape of this array is: ", random_.shape,'\n')
print("the type of this array is: ", type(random_),'\n')
print("the data type of this array is: ", (random_.dtype),'\n')


the random_ array looks like: 

 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]
 [0.76456045 0.0208098  0.13521018 0.11627302 0.30989758]] 

the dimention of this array is:  2 

the shape of this array is:  (5, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [126]:
#Using loop


for values_ in random_:
    print("the random_ array looks like: \n\n", values_,'\n')
    print("the dimention of this array is: ", values_.ndim,'\n')
    print("the shape of this array is: ", values_.shape,'\n')
    print("the type of this array is: ", type(values_),'\n')
    print("the data type of this array is: ", (values_.dtype),'\n')
    
    print('    ')
    
    dummy_array_ = np.append(dummy_array_, [values_], axis = 0)


the random_ array looks like: 

 [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496] 

the dimention of this array is:  1 

the shape of this array is:  (5,) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 

    
the random_ array looks like: 

 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932] 

the dimention of this array is:  1 

the shape of this array is:  (5,) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 

    
the random_ array looks like: 

 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923] 

the dimention of this array is:  1 

the shape of this array is:  (5,) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 

    
the random_ array looks like: 

 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675] 

the dimention of this array is:  1 

the shape of this array is:  (5,) 

the type of this array is:  <class

In [127]:
print("the random_ array looks like: \n\n", dummy_array_,'\n')
print("the dimention of this array is: ", dummy_array_.ndim,'\n')
print("the shape of this array is: ", dummy_array_.shape,'\n')
print("the type of this array is: ", type(dummy_array_),'\n')
print("the data type of this array is: ", (dummy_array_.dtype),'\n')

the random_ array looks like: 

 [[0.         0.         0.         0.         0.        ]
 [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]
 [0.76456045 0.0208098  0.13521018 0.11627302 0.30989758]] 

the dimention of this array is:  2 

the shape of this array is:  (6, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [128]:
#Here, we have created dummy_random_array_, now we will extract the array_

array_ = dummy_array_[1:]

print("the array looks like: \n\n", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')
print("the shape of this array is: ", array_.shape,'\n')
print("the type of this array is: ", type(array_),'\n')
print("the data type of this array is: ", (array_.dtype),'\n')

the array looks like: 

 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]
 [0.76456045 0.0208098  0.13521018 0.11627302 0.30989758]] 

the dimention of this array is:  2 

the shape of this array is:  (5, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [129]:
# modify the array, who has value less than 0.5, then add 0.5
array_ = np.where(array_>0.5, array_, array_ + 0.5)

print("the array looks like: \n\n", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')
print("the shape of this array is: ", array_.shape,'\n')
print("the type of this array is: ", type(array_),'\n')
print("the data type of this array is: ", (array_.dtype),'\n')

the array looks like: 

 [[0.65416284 0.7400497  0.76331502 0.53373939 0.51457496]
 [0.91874701 0.90071485 0.53342143 0.95694934 0.63720932]
 [0.78382835 0.60608318 0.94422514 0.85273554 0.50225923]
 [0.52122603 0.55203763 0.98537741 0.76813415 0.66071675]
 [0.76456045 0.5208098  0.63521018 0.61627302 0.80989758]] 

the dimention of this array is:  2 

the shape of this array is:  (5, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [130]:
row_ = []

for index_, values_ in enumerate(array_):
    check_ = (np.round(np.sum(array_[index_,:])))
    if check_ >= 4.0:
        print("row number_ = ",index_)
        row_.append(index_)
    else:
        continue
    
print(' ')
print("the list_ contains: ", row_)

row number_ =  1
row number_ =  2
 
the list_ contains:  [1, 2]


In [131]:
dummy_array_ = np.zeros((1, array_.shape[1]))

print("the dummy array looks like: \n", dummy_array_, '\n')

print('  ')

for values_ in row_:
    #Store the row in dummy_array_
    dummy_array_ = np.append(dummy_array_, [array_[values_, :]], axis = 0)
    #now delete the array
    array_       = np.delete(array_, values_, axis = 0)


print("after deleting, the array_ looks like: \n\n", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')
print("the shape of this array is: ", array_.shape,'\n')
print("the type of this array is: ", type(array_),'\n')
print("the data type of this array is: ", (array_.dtype),'\n')


print('  ')

dummy_array_ = dummy_array_[1:]

print("the dummy_array_ array_ looks like: \n\n", dummy_array_,'\n')
print("the dimention of this array is: ", dummy_array_.ndim,'\n')
print("the shape of this array is: ", dummy_array_.shape,'\n')
print("the type of this array is: ", type(dummy_array_),'\n')
print("the data type of this array is: ", (dummy_array_.dtype),'\n')

the dummy array looks like: 
 [[0. 0. 0. 0. 0.]] 

  
after deleting, the array_ looks like: 

 [[0.65416284 0.7400497  0.76331502 0.53373939 0.51457496]
 [0.78382835 0.60608318 0.94422514 0.85273554 0.50225923]
 [0.76456045 0.5208098  0.63521018 0.61627302 0.80989758]] 

the dimention of this array is:  2 

the shape of this array is:  (3, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 

  
the dummy_array_ array_ looks like: 

 [[0.91874701 0.90071485 0.53342143 0.95694934 0.63720932]
 [0.52122603 0.55203763 0.98537741 0.76813415 0.66071675]] 

the dimention of this array is:  2 

the shape of this array is:  (2, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [132]:
#How to delete works 
#np.delete(array_name, index, axis = 0/1)
array1_ = array_.copy()

np.delete(array1_, 1, axis = 0)

array([[0.65416284, 0.7400497 , 0.76331502, 0.53373939, 0.51457496],
       [0.76456045, 0.5208098 , 0.63521018, 0.61627302, 0.80989758]])

In [133]:
#Add 0.20 in all array

dummy_array_ = dummy_array_ + 0.20
array_       = array_ + 0.20

print("after adding 0.20 , the array_ looks like: \n\n", dummy_array_,'\n')
print("after adding 0.20 , the array_ looks like: \n\n", dummy_array_,'\n')

#merge the all sub array

array_ = np.vstack((dummy_array_, array_))


print("after merge, the array_ looks like: \n\n", array_,'\n')
print("the dimention of this array is: ", array_.ndim,'\n')
print("the shape of this array is: ", array_.shape,'\n')
print("the type of this array is: ", type(array_),'\n')
print("the data type of this array is: ", (array_.dtype),'\n')

after adding 0.20 , the array_ looks like: 

 [[1.11874701 1.10071485 0.73342143 1.15694934 0.83720932]
 [0.72122603 0.75203763 1.18537741 0.96813415 0.86071675]] 

after adding 0.20 , the array_ looks like: 

 [[1.11874701 1.10071485 0.73342143 1.15694934 0.83720932]
 [0.72122603 0.75203763 1.18537741 0.96813415 0.86071675]] 

after merge, the array_ looks like: 

 [[1.11874701 1.10071485 0.73342143 1.15694934 0.83720932]
 [0.72122603 0.75203763 1.18537741 0.96813415 0.86071675]
 [0.85416284 0.9400497  0.96331502 0.73373939 0.71457496]
 [0.98382835 0.80608318 1.14422514 1.05273554 0.70225923]
 [0.96456045 0.7208098  0.83521018 0.81627302 1.00989758]] 

the dimention of this array is:  2 

the shape of this array is:  (5, 5) 

the type of this array is:  <class 'numpy.ndarray'> 

the data type of this array is:  float64 



In [134]:
np.where(np.round(np.sum(array_, axis = 0)) >0.4 , 'T', 'F')

array(['T', 'T', 'T', 'T', 'T'], dtype='<U1')

In [140]:
#check something for me

list_ = [1,2,3,4,5,6,7,8,9,10]

[(values_ + 10) for values_ in list_]

# output:
# [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

#I want square all of those items

list_ = [[1,2,3], [4,5,6], [7,8,9]]

[[(value**2) for value in values_] for values_ in list_]

# output:
# [[1, 4, 9], [16, 25, 36], [49, 64, 81]]


list_ = [1,2,3,4,5,6,7,8,9,10]

func_ = list(map(lambda x: x + 10, list_))

func_

# output:
# [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

list_ = [[1,2,3], [4,5,6], [7,8,9]]

def function_(list_):
    func_ = list(map(lambda x: x ** 2, list_))
    return func_

list1_ = []
for values_ in list_:
    print(function_(values_))
    list1_.append(function_(values_))

print('   ')
list1_

# output:
# [[1, 4, 9], [16, 25, 36], [49, 64, 81]]

list_

def even_function_(list_):
    if list_%2==0:
        return True
    else:
        return False

list2_ = []

for values_ in list_:
    func_ = list(filter(even_function_, values_))
    print(func_)
    list2_.append(func_)

print('   ')
list2_

[1, 4, 9]
[16, 25, 36]
[49, 64, 81]
   
[2]
[4, 6]
[8]
   


[[2], [4, 6], [8]]

# Numpy Choice

In [174]:
list_ = [1,2,3,5]

In [172]:
choice_ = np.random.choice(list_)


condition_ = 4
while(condition_ !=0 ):
    print("choice = ", np.random.choice(list_))
    condition_ = condition_ - 1

choice =  3
choice =  2
choice =  1
choice =  3


In [175]:
func_ = list(filter(lambda x: x>2, list_))
func_

[3, 5]

# Reduce in List

In [180]:
list_ = [1, 2, 3, 4, 5]

#If i want to sum then 

# addition_ = 0

# for values_ in list_:
    
#     addition_ = addition_ + value_
    
# print("the addition is = ", addition_)

# output:
# the addition is =  15

#We can do this same things with 'reduce'. In order to do this, we will have to import fuctools

import functools

func_ = functools.reduce(lambda x,y: x+y, list_)
#here, we will have to pass two parameters in lambda(x,y)
func_

15

In [181]:
#First we will square all the elements

square_ = map(lambda x: )
func_   = functools.reduce(lambda x, y: x*y, [1,2,3,4,5])
func_

15