In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)

In [6]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

0.7489177489177489

In [7]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7705627705627706

In [8]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.7792207792207793

In [9]:
adb = DecisionTreeClassifier()
adb.fit(x_train,y_train)
adb.score(x_test,y_test)

0.7532467532467533

# Using Feature Selection with "Extra Tree Classifier"
1. For this I have to import extra tree classifier in Ensemble

In [10]:
from sklearn.ensemble import ExtraTreesClassifier

In [11]:
et = ExtraTreesClassifier()
et.fit(X,y)

ExtraTreesClassifier()

In [12]:
et.feature_importances_

array([0.10798545, 0.23868622, 0.09853148, 0.07918206, 0.07535787,
       0.14609585, 0.11639818, 0.13776288])

In [13]:
importance_Score_ = pd.DataFrame(et.feature_importances_, columns = ['Score'])
importance_Score_

Score
0  0.107985
1  0.238686
2  0.098531
3  0.079182
4  0.075358
5  0.146096
6  0.116398
7  0.137763

In [14]:
real_columns_ = df.columns
real_columns_ = pd.DataFrame(real_columns_)
real_columns_

0
0      6
1    148
2     72
3     35
4      0
5   33.6
6  0.627
7     50
8      1

In [15]:
data = pd.concat([real_columns_, importance_Score_],axis = 1)
selected_ = data.sort_values('Score',ascending = False).head(5)
selected_.drop('Score',axis = 1,inplace = True)

In [16]:
columns_ = pd.Series(selected_[0])

In [17]:
df = pd.read_csv('diabetes.csv',usecols=columns_)

In [18]:
df.head(5)

6  148  33.6  0.627  50
0  1   85  26.6  0.351  31
1  8  183  23.3  0.672  32
2  1   89  28.1  0.167  21
3  0  137  43.1  2.288  33
4  5  116  25.6  0.201  30

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

In [20]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7705627705627706

In [21]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

0.7402597402597403

In [22]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.7748917748917749

In [23]:
adb = AdaBoostClassifier()
adb.fit(x_train,y_train)
adb.score(x_test,y_test)

0.7619047619047619

# Feature Selection Using Random Forest

In [24]:
df = pd.read_csv('diabetes.csv')

In [25]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [26]:
X

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 2.66e+01, 3.51e-01, 3.10e+01],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 2.33e+01, 6.72e-01, 3.20e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 2.81e+01, 1.67e-01, 2.10e+01],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.62e+01, 2.45e-01, 3.00e+01],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.01e+01, 3.49e-01, 4.70e+01],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.04e+01, 3.15e-01, 2.30e+01]])

In [27]:
y

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,

In [28]:
rf = RandomForestClassifier()
rf.fit(X,y)

RandomForestClassifier()

In [29]:
rf.feature_importances_

array([0.08602879, 0.25674575, 0.09350947, 0.06709269, 0.07516626,
       0.15944567, 0.12516473, 0.13684663])

In [30]:
importance_ = pd.DataFrame(rf.feature_importances_)

In [31]:
real_columns_ = df.columns
real_columns_ = pd.DataFrame(real_columns_)

In [32]:
combined_ = pd.concat([real_columns_,importance_],axis=1)

In [33]:
combined_.columns =['Feature','Score']
combined_ = combined_.sort_values('Score', ascending = False).head(5)
combined_.drop('Score',axis = 1, inplace=True)

In [34]:
columns_ = pd.Series(combined_['Feature'])

In [35]:
df = pd.read_csv('diabetes.csv',usecols=columns_)
df.head()

148  72  33.6  0.627  50
0   85  66  26.6  0.351  31
1  183  64  23.3  0.672  32
2   89  66  28.1  0.167  21
3  137  40  43.1  2.288  33
4  116  74  25.6  0.201  30

In [36]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier()
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier()
adb.fit(x_train,y_train)
print("Adabost = ",adb.score(x_test,y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic =  0.7705627705627706
Decision Tree =  0.7489177489177489
Random Forest =  0.7662337662337663
Adabost =  0.7619047619047619


# Feature Selection Using Chi Square method
1. import "SelectKBest" in feature_selection
2. import "Chi" in feature_selection

In [37]:
df = pd.read_csv('diabetes.csv')
df.head(5)

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [38]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [39]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [40]:
model = SelectKBest(score_func=chi2, k = 7)
model.fit(X,y)
model.scores_

array([ 110.72718168, 1406.59049075,   17.50499769,   51.00789486,
       2219.39781908,  127.67149145,    5.35636428,  178.01076049])

In [41]:
score_ = pd.DataFrame(model.scores_)

In [42]:
real_columns = df.columns
real_columns = pd.DataFrame(real_columns)

feature_selection_ = pd.concat([real_columns, score_],axis = 1)
feature_selection_.columns = ['Features','Score']
columns_ = feature_selection_.sort_values('Score', ascending=False).head(5)
columns_.drop('Score',axis = 1, inplace=True)
columns_ = pd.Series(columns_['Features'])

In [43]:
df = pd.read_csv('diabetes.csv',usecols=columns_)

x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier()
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier()
adb.fit(x_train,y_train)
print("Adabost = ",adb.score(x_test,y_test))

Logistic =  0.7705627705627706
Decision Tree =  0.7489177489177489
Random Forest =  0.7748917748917749
Adabost =  0.7619047619047619


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Feature Selection Using "mutual_info_classif"

In [44]:
df = pd.read_csv('diabetes.csv')

In [45]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [46]:
from sklearn.feature_selection import mutual_info_classif
model = mutual_info_classif(X,y)
importance_ = pd.DataFrame(model)
real_columns = df.columns
real_columns = pd.DataFrame(real_columns)
feature_selection_ = pd.concat([real_columns,importance_],axis = 1)
feature_selection_.columns = ['Feature','Score']
columns_ = feature_selection_.sort_values('Score', ascending=False).head(5)
columns_.drop('Score',axis = 1, inplace=True)
columns_ = pd.Series(columns_['Feature'])

In [47]:
df = pd.read_csv('diabetes.csv',usecols=columns_)

x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier()
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier()
adb.fit(x_train,y_train)
print("Adabost = ",adb.score(x_test,y_test))

Logistic =  0.7705627705627706
Decision Tree =  0.7662337662337663
Random Forest =  0.7662337662337663
Adabost =  0.7619047619047619


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [48]:
df = pd.read_csv('titanic.csv')

In [49]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [50]:
df.dropna(inplace=True)

In [51]:
df.shape

(183, 12)

In [52]:
target_ = df['Survived']

In [53]:
df.drop('Survived',axis = 1, inplace= True)

In [54]:
df.drop('PassengerId', axis = 1, inplace= True)

In [55]:
df.drop('Name', axis = 1, inplace= True)

In [56]:
df = pd.get_dummies(df,drop_first=True)

In [57]:
df.shape

(183, 266)

In [58]:
X = df.iloc[:].values
y = target_.values

In [59]:
from sklearn.feature_selection import mutual_info_classif
model = mutual_info_classif(X,y)
importance_ = pd.DataFrame(model)
real_columns = df.columns
real_columns = pd.DataFrame(real_columns)
feature_selection_ = pd.concat([real_columns,importance_],axis = 1)
feature_selection_.columns = ['Feature','Score']
columns_ = feature_selection_.sort_values('Score', ascending=False).head(20)
columns_.drop('Score',axis = 1, inplace=True)
columns_ = pd.Series(columns_['Feature'])

In [60]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier(n_estimators=200)
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier()
adb.fit(x_train,y_train)
print("Adabost = ",adb.score(x_test,y_test))


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic =  0.7636363636363637
Decision Tree =  0.7636363636363637
Random Forest =  0.8181818181818182
Adabost =  0.8


In [61]:
df = pd.read_csv('titanic.csv')

In [62]:
df.dropna(inplace=True)

In [63]:
target_ = df['Survived']
df.drop('Survived',axis = 1, inplace= True)
df.drop('PassengerId', axis = 1, inplace= True)
df.drop('Name', axis = 1, inplace= True)
df = pd.get_dummies(df,drop_first=True)
X = df.iloc[:].values
y = target_.values


x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier()
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier()
adb.fit(x_train,y_train)
print("Adabost = ",adb.score(x_test,y_test))

Logistic =  0.7636363636363637
Decision Tree =  0.7636363636363637
Random Forest =  0.8181818181818182
Adabost =  0.7818181818181819


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [64]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data',na_values=['?','??','???'])

In [65]:
df.head(15)

1000025  5   1  1.1  1.2  2   1.3  3  1.4  1.5  2.1
0   1002945  5   4    4    5  7  10.0  3    2    1    2
1   1015425  3   1    1    1  2   2.0  3    1    1    2
2   1016277  6   8    8    1  3   4.0  3    7    1    2
3   1017023  4   1    1    3  2   1.0  3    1    1    2
4   1017122  8  10   10    8  7  10.0  9    7    1    4
5   1018099  1   1    1    1  2  10.0  3    1    1    2
6   1018561  2   1    2    1  2   1.0  3    1    1    2
7   1033078  2   1    1    1  2   1.0  1    1    5    2
8   1033078  4   2    1    1  2   1.0  2    1    1    2
9   1035283  1   1    1    1  1   1.0  3    1    1    2
10  1036172  2   1    1    1  2   1.0  2    1    1    2
11  1041801  5   3    3    3  2   3.0  4    4    1    4
12  1043999  1   1    1    1  2   3.0  3    1    1    2
13  1044572  8   7    5   10  7   9.0  5    5    4    4
14  1047630  7   4    6    4  6   1.0  4    3    1    4

In [66]:
df.shape

(698, 11)

In [67]:
df.isnull().sum()

1000025     0
5           0
1           0
1.1         0
1.2         0
2           0
1.3        16
3           0
1.4         0
1.5         0
2.1         0
dtype: int64

In [68]:
df['1.3'].fillna(df['1.3'].value_counts().sort_values(ascending=False).index[0],inplace=True)

In [69]:
df.isnull().sum()

1000025    0
5          0
1          0
1.1        0
1.2        0
2          0
1.3        0
3          0
1.4        0
1.5        0
2.1        0
dtype: int64

In [70]:
df.drop('1000025',axis = 1, inplace=True)

In [71]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values


x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier(n_estimators=200)
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier(n_estimators=200)
adb.fit(x_train,y_train)
print("Adabost = ",adb.score(x_test,y_test))


svc = SVC(gamma='auto', kernel='linear')
svc.fit(x_train,y_train)
print("SVC = ",svc.score(x_test,y_test))

Logistic =  0.9571428571428572
Decision Tree =  0.9619047619047619
Random Forest =  0.9523809523809523
Adabost =  0.9476190476190476
SVC =  0.9666666666666667


In [72]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data',na_values=['?','??','???'])

In [73]:
df['1.3'].fillna(df['1.3'].value_counts().sort_values(ascending=False).index[0],inplace=True)

In [74]:
df.drop('1000025',axis = 1, inplace=True)

In [75]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [76]:
from sklearn.feature_selection import mutual_info_classif
model = mutual_info_classif(X,y)
importance_ = pd.DataFrame(model)
real_columns = df.columns
real_columns = pd.DataFrame(real_columns)
feature_selection_ = pd.concat([real_columns,importance_],axis = 1)
feature_selection_.columns = ['Feature','Score']
columns_ = feature_selection_.sort_values('Score', ascending=False).head(5)
columns_.drop('Score',axis = 1, inplace=True)
columns_ = pd.Series(columns_['Feature'])
columns_

1      1
2    1.1
5    1.3
6      3
4      2
Name: Feature, dtype: object

In [77]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state=0)

lr = LogisticRegression()
lr.fit(x_train,y_train)
print("Logistic      = ",lr.score(x_test,y_test))

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print("Decision Tree = ",dt.score(x_test,y_test))

rf = RandomForestClassifier(n_estimators=200)
rf.fit(x_train,y_train)
print("Random Forest = ",rf.score(x_test,y_test))

adb = AdaBoostClassifier(n_estimators=200)
adb.fit(x_train,y_train)
print("Adabost       = ",adb.score(x_test,y_test))

svc = SVC(gamma='auto', kernel='linear')
svc.fit(x_train,y_train)
print("SVC           = ",svc.score(x_test,y_test))

Logistic      =  0.9571428571428572
Decision Tree =  0.9476190476190476
Random Forest =  0.9571428571428572
Adabost       =  0.9476190476190476
SVC           =  0.9666666666666667
