In [1]:
import numpy as np

In [2]:
#create a numpy array
array_ = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#Find the type
type(array_)

numpy.ndarray

In [4]:
#fine the shape
array_.shape
# outout: (3,3)

(3, 3)

In [5]:
#Slicing 
array_

# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

#if i want to retrieve 5 then 

print("the value is = ",array_[1,1])

#If i want to retrieve 8,9 then 

print("the values are = ",array_[2,1:])
#OR
print("the values are = ",array_[2,[1,2]])

#If i want to take 1,2,3 and 4,5,6 then

print("the values are = ",array_[:2, :])

#OR
print("the values are = ",array_[[0,1],:])

#If i want to take just 9 then

print("the value is = ",array_[2,2])

the value is =  5
the values are =  [8 9]
the values are =  [8 9]
the values are =  [[1 2 3]
 [4 5 6]]
the values are =  [[1 2 3]
 [4 5 6]]
the value is =  9


In [6]:
#Slicing continued

import random as rd
#in 'np.random.rand(row,column)'
array_ = np.random.rand(3,4)
print(array_)
print(array_.shape)

#If i want to print last two row

print("the vales are = ",array_[1:,:])
print(type(array_[1:,:]))

# list_ = list(array_[1:,:])
# print(list_[0])

#If i want to print data type then 'dtype'
print("the data type is = ",array_.dtype)

#If i want to print 'dimention' then use ndim

print("the dimention is = ",array_.ndim)

[[0.29255751 0.01451849 0.55566965 0.25027309]
 [0.40599394 0.5336012  0.71310306 0.63800011]
 [0.46186936 0.74213717 0.57555082 0.18154785]]
(3, 4)
the vales are =  [[0.40599394 0.5336012  0.71310306 0.63800011]
 [0.46186936 0.74213717 0.57555082 0.18154785]]
<class 'numpy.ndarray'>
the data type is =  float64
the dimention is =  2


In [7]:
#np.zeros
array_ = np.zeros(10)
array_
#If i just give one parameter then it will take that one as a 'row'

array_ = np.zeros((3,4), dtype = 'int64')
#It means 3 row and 4 columns
array_

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [8]:
#Create a numpy array where 3 rows and 4 columns

array_ = np.random.rand(3,4)
print("the array is: \n",array_)
print("the shape is:", array_.shape)
print("the dimention is = ",array_.ndim)

#create a numpy zeros where we will save the slicing data

zeros_ = np.zeros((2,3), dtype = 'float')
print('zeros_ values are:\n', zeros_)

#i want to put this "0.15817498" value into zeros

zeros_[0,0] = array_[0,1]
# zeros_
zeros_[0,1:] = array_[0,2:]
# zeros_
zeros_[1,-1] = array_[0,-1]
# zeros_
zeros_[1,:2] = array_[2,0:2]
zeros_

the array is: 
 [[0.45839137 0.72892914 0.77094606 0.53717392]
 [0.67064682 0.24205727 0.8235363  0.19477005]
 [0.08544711 0.71793648 0.8955558  0.20121506]]
the shape is: (3, 4)
the dimention is =  2
zeros_ values are:
 [[0. 0. 0.]
 [0. 0. 0.]]


array([[0.72892914, 0.77094606, 0.53717392],
       [0.08544711, 0.71793648, 0.53717392]])

In [9]:
np.arange(10)

#output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#but i want to take 2 rows and 5 columns then how to do in this case. just use 'reshape(row, column)'
array_ = np.arange(10).reshape(2,5)
print("the array is: \n",array_)
print("the data type is = ",array_.dtype)
print("the shape of this = ", array_.shape)
print("the dimention of this is = ", array_.ndim)
#if i want to save this same data into another np array then 

copy_ = np.zeros((2,5))
copy_ = array_

print("the copy array is :\n", copy_)

the array is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
the data type is =  int32
the shape of this =  (2, 5)
the dimention of this is =  2
the copy array is :
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
array_ = np.random.rand(2,5)
print(array_)
print(array_.dtype)
#but i want to change the type
array_ = array_.astype('int32')
array_

[[0.10963536 0.48363084 0.29094788 0.64993863 0.58860834]
 [0.80471601 0.55138087 0.28945153 0.36730899 0.45627878]]
float64


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
array_ = np.array([2.90, 3.87, 5.78])
print(array_)
#now change the data type

array_ = array_.astype('int64')
array_ 

[2.9  3.87 5.78]


array([2, 3, 5], dtype=int64)

In [12]:
#Created 3D data

array_ = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
print("the array is \n",array_)
print('the dimention is = ', array_.ndim)
print('the shape is = ', array_.shape)

#if i want to take 5 data then

print('the data is = ',array_[0,1][1])

the array is 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
the dimention is =  3
the shape is =  (1, 3, 3)
the data is =  5


In [13]:
#Using Np.where - it only work in numpy array

list_ = [1,2,3]
list_ = np.array(list_)
list1_ = np.where(list_>2, 'T', 'F')
for index, value in enumerate(list1_):
    if value == 'T':
        print(list_[index])
    else:
        continue

3


In [14]:
#Boolean Indexing

array_ = np.arange(0,10).reshape(2,5)
print("the array is: \n",array_)

bool_ = [True, False, True, False, True, True, False, False, True, False]
bool_ = np.array(bool_).reshape(2,5)
print("the boolean is:\n",bool_)

print("the dimention of array is = ", array_.ndim)
print("the dimention of bool_ is = ",bool_.ndim)

# array_[bool_ == True]

# for array, bool_ in zip(array_,bool_):

data_ = np.where(bool_ == True, array_,'false')
print("the data_ is: \n",data_)


the array is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
the boolean is:
 [[ True False  True False  True]
 [ True False False  True False]]
the dimention of array is =  2
the dimention of bool_ is =  2
the data_ is: 
 [['0' 'false' '2' 'false' '4']
 ['5' 'false' 'false' '8' 'false']]


In [15]:
array_ = np.arange(0,20).reshape(4,5)
print(array_)
np.delete(array_, np.where(array_%2==0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
array_
list_ =  []
for i in array_:
    list_.append(np.delete(i, np.where(i%2==0)))
list_

[array([1, 3]), array([5, 7, 9]), array([11, 13]), array([15, 17, 19])]

In [17]:
list(list_)

[array([1, 3]), array([5, 7, 9]), array([11, 13]), array([15, 17, 19])]

In [18]:
#Delete the data in numpy: 1D array

array_ = np.array([1,2,3,4,5,6,7,8,9,10])
array_
print('dim = ',array_.ndim)
print('shape = ', array_.shape)

#if i want to delete 4 then 

print("after deleting the value is = ",np.delete(array_, 3))

#here, np.delete(array, index, axis = 0/1)
#if i want to multiple data:

print("after deeleting the index 0, 1, 2 : ",np.delete(array_,[0,1,2]))

#it's time consuming, so we should use loop

array_

# for index_, value_ in enumerate(array_):
#     print(index_, value_)

indexList_ = []
for index_, value_ in enumerate(array_):
    if value_ == 4:
        indexList_.append(index_)
    elif value_ == 5:
        indexList_.append(index_)
    elif value_ == 6:
        indexList_.append(index_)
    else:
        continue
indexList_

print("after deleting the value is = ",np.delete(array_,indexList_))


dim =  1
shape =  (10,)
after deleting the value is =  [ 1  2  3  5  6  7  8  9 10]
after deeleting the index 0, 1, 2 :  [ 4  5  6  7  8  9 10]
after deleting the value is =  [ 1  2  3  7  8  9 10]


In [19]:
#Delete in 2D array

array_ = np.arange(0,20).reshape(4,5)
print("the array is: \n",array_)
print("the dimention is: ", array_.ndim)
print('the shape is:', array_.shape)

#if i want to delete first two rows then

print("after deleting the fisrt and second row: \n",np.delete(array_, [0,1], axis = 0))

#if i want to delete last 3 columns

print("after deleting the last 3 columns: \n",np.delete(array_, [1,2,3,4], axis = 1))

the array is: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
the dimention is:  2
the shape is: (4, 5)
after deleting the fisrt and second row: 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
after deleting the last 3 columns: 
 [[ 0]
 [ 5]
 [10]
 [15]]


In [20]:
#Practise So far

def function_(array_):
    print("the array is: \n\n",array_,'\n')
    print('the dimention of this array is:',array_.ndim,'\n')
    print('the data type of this array is:',array_.dtype,'\n')
    print('the shape of this array is    :',array_.shape,'\n')
    print('the num of rows in this array :',array_.shape[0],'\n')
    print('the num of col in this array  :',array_.shape[1],'\n')
    
    rowIndex_    = np.arange(array_.shape[0])
    columnIndex_ = np.arange(array_.shape[1])
    
    print("row index are   : ",rowIndex_,'\n')
    print("column index are:", columnIndex_,'\n')
    
    for row_ in rowIndex_:
        for column_ in columnIndex_:
            print(array_[row_, column_],'\n')
        print('-----------------------------------------------------')
    
    store_ = np.zeros((array_.shape[0], array_.shape[1]))
    print('Zero array is:\n', store_,'\n')
    
    index = []
    value_ = []
    dict_  = {}
    for index_, values_ in enumerate(array_):
        index.append(index_)
        value_.append(values_)
    print("Index are = ",index,'\n')
    print("values are = \n", value_,'\n')
    
    for i in index:
        store_[i,:] = value_[i] 
        dict_[i]    = list(value_[i])
    print("after store the array looks like :\n",store_,'\n')
    print("In dictonary the value is = ",dict_)
    
    return store_, dict_
array_ = np.random.rand(4,5)
array_, dict_ = function_(array_)

the array is: 

 [[0.47099763 0.12586475 0.53347071 0.91232057 0.43037897]
 [0.51618139 0.69285829 0.8308664  0.2891784  0.73226046]
 [0.96445581 0.5348438  0.18992495 0.22052744 0.22118184]
 [0.58386188 0.05403938 0.43145181 0.20255498 0.35486133]] 

the dimention of this array is: 2 

the data type of this array is: float64 

the shape of this array is    : (4, 5) 

the num of rows in this array : 4 

the num of col in this array  : 5 

row index are   :  [0 1 2 3] 

column index are: [0 1 2 3 4] 

0.4709976269982299 

0.12586474571950856 

0.5334707077051077 

0.9123205691620963 

0.43037897057249197 

-----------------------------------------------------
0.5161813894773942 

0.6928582937490858 

0.8308664002422798 

0.28917839773239273 

0.7322604647070858 

-----------------------------------------------------
0.9644558056638771 

0.5348438027499443 

0.18992494910297475 

0.22052743702086364 

0.22118183940475744 

-----------------------------------------------------
0.583861880

In [21]:
#The array is
print(array_)

[[0.47099763 0.12586475 0.53347071 0.91232057 0.43037897]
 [0.51618139 0.69285829 0.8308664  0.2891784  0.73226046]
 [0.96445581 0.5348438  0.18992495 0.22052744 0.22118184]
 [0.58386188 0.05403938 0.43145181 0.20255498 0.35486133]]


In [22]:
#The dictonary is
print(dict_)

{0: [0.4709976269982299, 0.12586474571950856, 0.5334707077051077, 0.9123205691620963, 0.43037897057249197], 1: [0.5161813894773942, 0.6928582937490858, 0.8308664002422798, 0.28917839773239273, 0.7322604647070858], 2: [0.9644558056638771, 0.5348438027499443, 0.18992494910297475, 0.22052743702086364, 0.22118183940475744], 3: [0.5838618804229811, 0.054039378366507185, 0.43145180887876666, 0.20255498193989485, 0.3548613290991648]}


In [23]:
#Find the max
print("max value is = ",array_.max())
#Find the min
print("Min value is = ",array_.min())
#Find the argmax - it will return index
print("The index of max is = ", array_.argmax())
#Find the argmin - it will return the index
print("the index of min is = ", array_.argmin())

max value is =  0.9644558056638771
Min value is =  0.054039378366507185
The index of max is =  10
the index of min is =  16


In [24]:
#Delete the first two columns

array_ = np.delete(array_, [0,1], axis = 1)

print("after deleting the array looks like: \n", array_,'\n')

after deleting the array looks like: 
 [[0.53347071 0.91232057 0.43037897]
 [0.8308664  0.2891784  0.73226046]
 [0.18992495 0.22052744 0.22118184]
 [0.43145181 0.20255498 0.35486133]] 



In [25]:
#Delete the last two rows

array_ = np.delete(array_,[-1,-2], axis = 0)

print("after deleting the rows the array looks like: \n", array_,'\n')

after deleting the rows the array looks like: 
 [[0.53347071 0.91232057 0.43037897]
 [0.8308664  0.2891784  0.73226046]] 



In [26]:
#Modilfy something(Update)

bool_ = np.where(array_>0.50, 'T','F')
print(bool_)

[['T' 'T' 'F']
 ['T' 'F' 'T']]


In [27]:
new_ = np.where(bool_ == 'T', array_,' ')
print(new_)

[['0.5334707077051077' '0.9123205691620963' ' ']
 ['0.8308664002422798' ' ' '0.7322604647070858']]


In [28]:
np.where(new_ != ' ', new_, 'False')

array([['0.5334707077051077', '0.9123205691620963', 'False'],
       ['0.8308664002422798', 'False', '0.7322604647070858']],
      dtype='<U32')

In [29]:
print("the array = ",array_[array_>0.5])

the array =  [0.53347071 0.91232057 0.8308664  0.73226046]


In [30]:
intArray_ = array_[array_>0.5].astype('int64')
print("the int array is = ", intArray_)

the int array is =  [0 0 0 0]


In [31]:
array_ = np.array([1,2,1,2])
array_

#Find the unique 

np.unique(array_)

array([1, 2])

In [32]:
array_ = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(array_, return_counts=True)

print(unique, counts)
hello = np.asarray((unique,counts)).T

hello.sort()

hello

[ 1  2  5 25] [5 3 1 1]


array([[ 1,  5],
       [ 2,  3],
       [ 1,  5],
       [ 1, 25]], dtype=int64)

In [33]:
list_ = [1,2,3,4]
list1_ = [5,6,7,8]

for value1_, value2_ in zip(list_,list1_):
    print(value1_,value2_)

1 5
2 6
3 7
4 8


In [34]:
dict_ = {1:10, 2:20, 3:30}
dict_

{1: 10, 2: 20, 3: 30}

In [35]:
dict_[3] = 40
dict_

{1: 10, 2: 20, 3: 40}

In [36]:
upadate_ = {3:1000}

dict_.update(upadate_)
dict_

{1: 10, 2: 20, 3: 1000}

In [37]:
array_ = np.array(dict_)
print(array_)

{1: 10, 2: 20, 3: 1000}


In [38]:
keys = []
items = []
for keys_, items_ in dict_.items():
    print(keys_, items_)
    keys.append(keys_)
    items.append(items_)
keys

1 10
2 20
3 1000


[1, 2, 3]

In [39]:
for keys_, values_ in zip(keys,items):
    print((keys_, values_))

(1, 10)
(2, 20)
(3, 1000)


In [40]:
array_ = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])

In [41]:
array_

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
array_ = array_.T

In [43]:
array_
array_.sum(axis = 0)

array([10, 26, 42])

In [44]:
array_.sum(axis = 1)

array([15, 18, 21, 24])

In [45]:
array_.sort(0)
array_

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [46]:
array_[np.in1d(array_, [12,7,11]).reshape(4,3)]

array([ 7, 11, 12])

In [47]:
data_ = np.where(array_ == 12)
print(data_)

(array([3], dtype=int64), array([2], dtype=int64))


In [48]:
array_[3][2]

12

In [49]:
data_ = np.where(np.in1d(array_, [3,4,8]))
data_

(array([ 6,  9, 10], dtype=int64),)

In [50]:
row_= array_.shape[0]
col_ = array_.shape[1]

print(row_, col_)

4 3


In [51]:
row = np.arange(4, dtype = 'int64')
col = np.arange(3, dtype = 'int64')

dict_ = {}
count = 0
for i in row:
    for j in col:
        dict_[count] = [i,j]
        count = count + 1
print(dict_)

retrive = dict_[6]
print("That search value is = ",retrive)

row = retrive[0]
col = retrive[1]
array_[row][col]

{0: [0, 0], 1: [0, 1], 2: [0, 2], 3: [1, 0], 4: [1, 1], 5: [1, 2], 6: [2, 0], 7: [2, 1], 8: [2, 2], 9: [3, 0], 10: [3, 1], 11: [3, 2]}
That search value is =  [2, 0]


3

In [52]:
def function_(value_):
    
    row_= array_.shape[0]
    col_ = array_.shape[1]
    
    row = np.arange(4, dtype = 'int64')
    col = np.arange(3, dtype = 'int64')

    dict_ = {}
    count = 0
    for i in row:
        for j in col:
            dict_[count] = [i,j]
            count = count + 1
    return dict_[value_]

In [53]:
print("The array is: \n",array_,'\n')

#Find the value is presence or not

Index_ = np.where(np.in1d(array_, [5,8,1]))

print(Index_)
# Index_
# for value in range(3):
#     print("Index is = ", function_(Index_[0][value]))

# Index_
#when we will call it then this kind of output will be occured, in that case if we convert it to a list then nothing can be changed
#so, what we will have to do is Index[0], then we will convert to it as a list then we will get solution
# output: (array([ 0,  1, 10], dtype=int64),)

list_ = list(Index_[0])
length_ = len(list_)

for i in (list_):
    print("the value of ",i,',and its index is = ',function_(i))
    

The array is: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] 

(array([ 0,  1, 10], dtype=int64),)
the value of  0 ,and its index is =  [0, 0]
the value of  1 ,and its index is =  [0, 1]
the value of  10 ,and its index is =  [3, 1]


In [54]:
list_ = list(Index_[0])
len(list_)

3

In [1]:
import numpy as np

In [2]:
array_ = np.array([[1,2,3],[4,5,6]])
array_

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# for i in array_:
#     print(i)
  
#if i run this code then the output will be:
# output:
# [1 2 3]
# [4 5 6]

[1 2 3]
[4 5 6]


In [8]:
for i in np.nditer(array_):
    print(i)

1
2
3
4
5
6


In [17]:
#asarray(input - (tuple, list, any combination), dtype, order = (c - row, F- column))

list_ = [1,2,3,4,5,6]

print(list_)

array_ = np.asarray(list_, dtype = 'int64').reshape(2,3).T

print(array_)

[1, 2, 3, 4, 5, 6]
[[1 4]
 [2 5]
 [3 6]]


In [34]:
array1_ = np.array([[1,2,3],[1,2,3],[4,5,1]])
print(array1_)
print('------------------------------------------')

unique, counts_ = np.unique(array1_, return_counts=True)
print(unique)
print('------------------------------------------')
print(counts_)
print('------------------------------------------')

array_ = np.asarray((unique,counts_)).T
print(array_)

[[1 2 3]
 [1 2 3]
 [4 5 1]]
------------------------------------------
[1 2 3 4 5]
------------------------------------------
[3 2 2 1 1]
------------------------------------------
[[1 3]
 [2 2]
 [3 2]
 [4 1]
 [5 1]]


In [43]:
#Linspace

[int(data_) for data_ in np.linspace(start = 1, stop = 50, num = 50)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [52]:
#array_split
array_ = np.arange(10).reshape(5,2)
array_

data_ = np.array_split(array_,3)
data_[0]

array([[0, 1],
       [2, 3]])

In [53]:
array_ = np.arange(100).reshape(20,5)
array_

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [54]:
#Now split this array into 5 parts

split_ = np.array_split(array_, 5)

In [57]:
print("first split value is: \n",split_[0],'\n')
print("second split value is: \n",split_[1],'\n')
print("third split value is: \n",split_[2],'\n')
print("fourth split value is: \n",split_[3],'\n')
print("fifth split value is: \n",split_[4],'\n')

first split value is: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

second split value is: 
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

third split value is: 
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]] 

fourth split value is: 
 [[60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]] 

fifth split value is: 
 [[80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]] 



In [63]:
#Now join this

join_ = np.vstack([split_[0], split_[1], split_[2], split_[3],split_[4]])
join_

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [64]:
array_

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [66]:
array_ in join_

True

In [69]:
check_ = array_[5,:4]
print(check_)

[25 26 27 28]


In [81]:
array_[np.in1d(array_, [99,1,2,3,55]).reshape(20,5)]

array([ 1,  2,  3, 55, 99])

In [87]:
def function_(value_):
    
    row_= array_.shape[0]
    col_ = array_.shape[1]
    
    row = np.arange(row_, dtype = 'int64')
    col = np.arange(col_, dtype = 'int64')

    dict_ = {}
    count = 0
    for i in row:
        for j in col:
            dict_[count] = [i,j]
            count = count + 1
    return dict_[value_]


In [91]:
index_ = np.where(np.in1d(array_, [99,1,2,3,55]))
index_ = list(index_[0])

for i in index_:
    print(function_(i))

[0, 1]
[0, 2]
[0, 3]
[11, 0]
[19, 4]


In [103]:
#Difference between view and copy


array_ = np.array([[10,20,30],[40,50,60]])
print(array_)

take_ = array_[:,:2]
print(take_)

#now modify the array

take_[:] = 100
print(take_)

#now print the real array_
print(array_)
#it just changed the whole array:

#In order to prevent this, what we will have to do is using '.copy()'

take_ = array_[:,:2].copy()

print(take_)

take_[:] = -1

print(take_)
#now print the real array; it will not be changed
print(array_)

[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]]
[[100 100]
 [100 100]]
[[100 100  30]
 [100 100  60]]
[[100 100]
 [100 100]]
[[-1 -1]
 [-1 -1]]
[[100 100  30]
 [100 100  60]]


# Numpy
1. How to find Data Type
2. How to find Dimention
3. How to Find Shape
4. How to Slice
5. How to Use np.(Zeros, ones, random.rand, arange, shape)
6. How to store Data Using (5)
7. How to Update Value, Delete from 1D, 2D
8. How to Find the data and index using (np.in1D and np.where)
9. Using np.where()
10. Using np.in1d
11. Using asarray
12. Using unique
12.1 Using linspace
13. Using Vstack, hstack
14. How to Split the whole dataset into sub dataset